WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-env-00.bqd_015_raw.LN_PPSL_raw 
),   
 
CTE_2  AS  ( 
SELECT
	CAST(column_name  AS  bigquery_type)  AS  column_name,
	CAST(Appl_Id  AS  STRING)  AS  Appl_Id,
	CAST(Appl_Nbr  AS  STRING)  AS  Appl_Nbr,
	CAST(Appl_Control_Fields  AS  STRING)  AS  Appl_Control_Fields,
	CAST(Appl_Ppsl_Seq_Nbr  AS  NUMERIC)  AS  Appl_Ppsl_Seq_Nbr,
	CAST(Admin_Code  AS  STRING)  AS  Admin_Code,
	CAST(Advance_Dte  AS  DATE)  AS  Advance_Dte,
	CAST(Agent_Code  AS  STRING)  AS  Agent_Code,
	CAST(Appl_Source  AS  STRING)  AS  Appl_Source,
	CAST(Apply_Ln_Amt  AS  NUMERIC)  AS  Apply_Ln_Amt,
	CAST(Apply_Nbr_Of_Insl  AS  NUMERIC)  AS  Apply_Nbr_Of_Insl,
	CAST(Aprov_Ln_Amt  AS  NUMERIC)  AS  Aprov_Ln_Amt,
	CAST(Aprov_Nbr_Of_Insl  AS  NUMERIC)  AS  Aprov_Nbr_Of_Insl,
	CAST(Asset_Class  AS  STRING)  AS  Asset_Class,
	CAST(Chrg_Code  AS  STRING)  AS  Chrg_Code,
	CAST(Compliance_Result  AS  STRING)  AS  Compliance_Result,
	CAST(Corr_Add  AS  STRING)  AS  Corr_Add,
	CAST(Cr_Facility_Ind  AS  STRING)  AS  Cr_Facility_Ind,
	CAST(Cr_Line_Ind  AS  STRING)  AS  Cr_Line_Ind,
	CAST(Cust_CAP  AS  NUMERIC)  AS  Cust_CAP,
	CAST(Dealer_Code  AS  STRING)  AS  Dealer_Code,
	CAST(Dealer_Comm_Pct  AS  NUMERIC)  AS  Dealer_Comm_Pct,
	CAST(Dealer_Guarantee_Ind  AS  STRING)  AS  Dealer_Guarantee_Ind,
	CAST(DSR_Val  AS  NUMERIC)  AS  DSR_Val,
	CAST(DSR2_Val  AS  NUMERIC)  AS  DSR2_Val,
	CAST(ETI  AS  NUMERIC)  AS  ETI,
	CAST(Facility_Appl_Id  AS  STRING)  AS  Facility_Appl_Id,
	CAST(Facility_Acct_Nbr  AS  STRING)  AS  Facility_Acct_Nbr,
	CAST(Facility_Control_Fields  AS  STRING)  AS  Facility_Control_Fields,
	CAST(Facility_Code  AS  STRING)  AS  Facility_Code,
	CAST(HKMC_Sale_Ind  AS  STRING)  AS  HKMC_Sale_Ind,
	CAST(HKMC_Prem_Type_Code  AS  STRING)  AS  HKMC_Prem_Type_Code,
	CAST(Hire_Purchase_Ind  AS  STRING)  AS  Hire_Purchase_Ind,
	CAST(Latest_Util_Amt  AS  NUMERIC)  AS  Latest_Util_Amt,
	CAST(Ln_Appl_Id  AS  STRING)  AS  Ln_Appl_Id,
	CAST(Ln_Acct_Nbr  AS  INT64)  AS  Ln_Acct_Nbr,
	CAST(Ln_Control_Fields  AS  STRING)  AS  Ln_Control_Fields,
	CAST(Ln_Ccy_Code  AS  STRING)  AS  Ln_Ccy_Code,
	CAST(Ln_Collat_Ratio  AS  NUMERIC)  AS  Ln_Collat_Ratio,
	CAST(Ln_Group_Code  AS  STRING)  AS  Ln_Group_Code,
	CAST(Ln_Income_Ratio  AS  NUMERIC)  AS  Ln_Income_Ratio,
	CAST(Ln_Net_Purchase_Ratio  AS  NUMERIC)  AS  Ln_Net_Purchase_Ratio,
	CAST(Ln_Purchase_Ratio  AS  NUMERIC)  AS  Ln_Purchase_Ratio,
	CAST(Ln_Use_Country  AS  STRING)  AS  Ln_Use_Country,
	CAST(Mail_Code  AS  STRING)  AS  Mail_Code,
	CAST(Max_Allow_Tenor  AS  NUMERIC)  AS  Max_Allow_Tenor,
	CAST(Mortgage_Plan_Code  AS  STRING)  AS  Mortgage_Plan_Code,
	CAST(Prod_CAP  AS  NUMERIC)  AS  Prod_CAP,
	CAST(Project_Code  AS  STRING)  AS  Project_Code,
	CAST(Promote_Code  AS  STRING)  AS  Promote_Code,
	CAST(Purpose_of_Fin_HKMA  AS  STRING)  AS  Purpose_of_Fin_HKMA,
	CAST(Rise_Mortgage_Rate_Pct  AS  NUMERIC)  AS  Rise_Mortgage_Rate_Pct,
	CAST(Seller_Name  AS  STRING)  AS  Seller_Name,
	CAST(Solicitor_Code  AS  STRING)  AS  Solicitor_Code,
	CAST(Stressed_DSR_Actual_Tenor  AS  NUMERIC)  AS  Stressed_DSR_Actual_Tenor,
	CAST(Stressed_DSR_Max_Tenor  AS  NUMERIC)  AS  Stressed_DSR_Max_Tenor,
	CAST(Stressed_Test_Dte  AS  DATE)  AS  Stressed_Test_Dte,
	CAST(TAV1_Val  AS  NUMERIC)  AS  TAV1_Val,
	CAST(TAV2_Val  AS  NUMERIC)  AS  TAV2_Val,
	CAST(Tax_Amt  AS  NUMERIC)  AS  Tax_Amt
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_NoFutureDate('Advance_Dte')}},
	{{validate_CountryCode('Ln_Use_Country')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
Advance_Dte,
Agent_Code,
Appl_Source,
Apply_Ln_Amt,
Apply_Nbr_Of_Insl,
Aprov_Ln_Amt,
Aprov_Nbr_Of_Insl,
Asset_Class,
Chrg_Code,
Compliance_Result,
Corr_Add,
Cr_Facility_Ind,
Cr_Line_Ind,
Cust_CAP,
Dealer_Code,
Dealer_Comm_Pct,
Dealer_Guarantee_Ind,
DSR_Val,
DSR2_Val,
ETI,
Facility_Appl_Id,
Facility_Acct_Nbr,
Facility_Control_Fields,
Facility_Code,
HKMC_Sale_Ind,
HKMC_Prem_Type_Code,
Hire_Purchase_Ind,
Latest_Util_Amt,
Ln_Appl_Id,
Ln_Acct_Nbr,
Ln_Control_Fields,
Ln_Ccy_Code,
Ln_Collat_Ratio,
Ln_Group_Code,
Ln_Income_Ratio,
Ln_Net_Purchase_Ratio,
Ln_Purchase_Ratio,
Ln_Use_Country,
Mail_Code,
Max_Allow_Tenor,
Mortgage_Plan_Code,
Prod_CAP,
Project_Code,
Promote_Code,
Purpose_of_Fin_HKMA,
Rise_Mortgage_Rate_Pct,
Seller_Name,
Solicitor_Code,
Stressed_DSR_Actual_Tenor,
Stressed_DSR_Max_Tenor,
Stressed_Test_Dte,
TAV1_Val,
TAV2_Val,
Tax_Amt,
	{{  aggregate_validation_columns(['__NoFutureDate_valid_Advance_Dte','__CountryCode_valid_Ln_Use_Country'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
