WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-env-00.bqd_015_raw.MAO_APPL_raw 
),   
 
CTE_2  AS  ( 
SELECT
	CAST(column_name  AS  bigquery_type)  AS  column_name,
	CAST(Doc_Nbr  AS  INT64)  AS  Doc_Nbr,
	CAST(Doc_Type_Code  AS  STRING)  AS  Doc_Type_Code,
	CAST(Issue_Country_Code  AS  STRING)  AS  Issue_Country_Code,
	CAST(Ref_Id  AS  STRING)  AS  Ref_Id,
	CAST(Submit_Dte  AS  DATE)  AS  Submit_Dte,
	CAST(Session_Id  AS  STRING)  AS  Session_Id,
	CAST(Acct_Nbr  AS  INT64)  AS  Acct_Nbr,
	CAST(Acct_Purpose  AS  STRING)  AS  Acct_Purpose,
	CAST(Add_Proof_Ind  AS  STRING)  AS  Add_Proof_Ind,
	CAST(API_Appl_ID  AS  STRING)  AS  API_Appl_ID,
	CAST(API_Dte  AS  DATE)  AS  API_Dte,
	CAST(API_Time  AS  STRING)  AS  API_Time,
	CAST(API_TSP_ID  AS  STRING)  AS  API_TSP_ID,
	CAST(Appl_Status  AS  STRING)  AS  Appl_Status,
	CAST(Appl_Type  AS  STRING)  AS  Appl_Type,
	CAST(ATM_Lang_Code  AS  STRING)  AS  ATM_Lang_Code,
	CAST(China_Id_Proof_Ind  AS  STRING)  AS  China_Id_Proof_Ind,
	CAST(Consent_Proof_Ind  AS  STRING)  AS  Consent_Proof_Ind,
	CAST(Corr_Add_Country_Code  AS  STRING)  AS  Corr_Add_Country_Code,
	CAST(Corr_Add_Line_1  AS  STRING)  AS  Corr_Add_Line_1,
	CAST(Corr_Add_Line_2  AS  STRING)  AS  Corr_Add_Line_2,
	CAST(Corr_Add_Line_3  AS  STRING)  AS  Corr_Add_Line_3,
	CAST(Corr_Add_Line_4  AS  STRING)  AS  Corr_Add_Line_4,
	CAST(Corr_Add_Type  AS  STRING)  AS  Corr_Add_Type,
	CAST(Create_Dte  AS  DATE)  AS  Create_Dte,
	CAST(CSS_Acct_Ind  AS  STRING)  AS  CSS_Acct_Ind,
	CAST(CSS_Advice_Type_Code  AS  STRING)  AS  CSS_Advice_Type_Code,
	CAST(CTP_Proof_Ind  AS  STRING)  AS  CTP_Proof_Ind,
	CAST(Device_Id  AS  STRING)  AS  Device_Id,
	CAST(Device_Model  AS  STRING)  AS  Device_Model,
	CAST(Device_OS_Ver  AS  STRING)  AS  Device_OS_Ver,
	CAST(Device_Platform  AS  STRING)  AS  Device_Platform,
	CAST(DK_Training_Ind  AS  STRING)  AS  DK_Training_Ind,
	CAST(DK_WorkExp_Ind  AS  STRING)  AS  DK_WorkExp_Ind,
	CAST(Doc_Expiry_Dte  AS  DATE)  AS  Doc_Expiry_Dte,
	CAST(DP_TradingExp_Ind  AS  STRING)  AS  DP_TradingExp_Ind,
	CAST(Dte_Of_Birth  AS  DATE)  AS  Dte_Of_Birth,
	CAST(Elect_Add  AS  STRING)  AS  Elect_Add,
	CAST(Employer_Consent_Declar  AS  STRING)  AS  Employer_Consent_Declar,
	CAST(Employer_Declar  AS  STRING)  AS  Employer_Declar,
	CAST(Employer_Name  AS  STRING)  AS  Employer_Name,
	CAST(Employment_Code  AS  STRING)  AS  Employment_Code,
	CAST(Exit_Page  AS  STRING)  AS  Exit_Page,
	CAST(FATCA_Ind  AS  STRING)  AS  FATCA_Ind,
	CAST(Fin_Status_Q1  AS  STRING)  AS  Fin_Status_Q1,
	CAST(Fin_Status_Q2  AS  STRING)  AS  Fin_Status_Q2,
	CAST(Fin_Status_Q3  AS  STRING)  AS  Fin_Status_Q3,
	CAST(Fin_Status_Q4  AS  STRING)  AS  Fin_Status_Q4,
	CAST(Fin_Status_Q5  AS  STRING)  AS  Fin_Status_Q5,
	CAST(Fin_Status_Q6  AS  STRING)  AS  Fin_Status_Q6,
	CAST(Fin_Status_Q6_Remark  AS  STRING)  AS  Fin_Status_Q6_Remark,
	CAST(Fin_Status_Q7  AS  STRING)  AS  Fin_Status_Q7,
	CAST(Fin_Status_Q8  AS  STRING)  AS  Fin_Status_Q8,
	CAST(GPS_Enabled  AS  STRING)  AS  GPS_Enabled,
	CAST(GPS_Latitude  AS  STRING)  AS  GPS_Latitude,
	CAST(GPS_Location  AS  STRING)  AS  GPS_Location,
	CAST(GPS_Longitude  AS  STRING)  AS  GPS_Longitude,
	CAST(HK_Perm_Resident  AS  STRING)  AS  HK_Perm_Resident,
	CAST(HK_Tax_Resident  AS  STRING)  AS  HK_Tax_Resident,
	CAST(HKID_Type_Code  AS  STRING)  AS  HKID_Type_Code,
	CAST(Industry_Code  AS  STRING)  AS  Industry_Code,
	CAST(IP_Addr  AS  STRING)  AS  IP_Addr,
	CAST(Job_Position  AS  STRING)  AS  Job_Position,
	CAST(Juris_Tax_Resident_1  AS  STRING)  AS  Juris_Tax_Resident_1,
	CAST(Juris_Tax_Resident_2  AS  STRING)  AS  Juris_Tax_Resident_2,
	CAST(Juris_Tax_Resident_3  AS  STRING)  AS  Juris_Tax_Resident_3,
	CAST(Juris_Tax_Resident_4  AS  STRING)  AS  Juris_Tax_Resident_4,
	CAST(Juris_Tax_Resident_5  AS  STRING)  AS  Juris_Tax_Resident_5,
	CAST(LDS_Acct_Ind  AS  STRING)  AS  LDS_Acct_Ind,
	CAST(Mobile_Phone_Country_Code  AS  STRING)  AS  Mobile_Phone_Country_Code,
	CAST(Mobile_Phone_Nbr  AS  STRING)  AS  Mobile_Phone_Nbr,
	CAST(Multi_Nationality  AS  STRING)  AS  Multi_Nationality,
	CAST(Nationality  AS  STRING)  AS  Nationality,
	CAST(Occup_Code  AS  STRING)  AS  Occup_Code,
	CAST(Optout_3rd_Party_Gain  AS  STRING)  AS  Optout_3rd_Party_Gain,
	CAST(Optout_Call  AS  STRING)  AS  Optout_Call,
	CAST(Optout_DM  AS  STRING)  AS  Optout_DM,
	CAST(Optout_Email  AS  STRING)  AS  Optout_Email,
	CAST(Optout_SI  AS  STRING)  AS  Optout_SI,
	CAST(Optout_SMS  AS  STRING)  AS  Optout_SMS,
	CAST(Other_Tax_Resident  AS  STRING)  AS  Other_Tax_Resident,
	CAST(Party_Chinese_Name  AS  STRING)  AS  Party_Chinese_Name,
	CAST(Party_Name  AS  STRING)  AS  Party_Name,
	CAST(PBK_Ref  AS  STRING)  AS  PBK_Ref,
	CAST(Prefer_CN_Br_Code  AS  STRING)  AS  Prefer_CN_Br_Code,
	CAST(Prefer_HK_Br_Code  AS  STRING)  AS  Prefer_HK_Br_Code,
	CAST(Prod_Type  AS  STRING)  AS  Prod_Type,
	CAST(Referral_Code  AS  STRING)  AS  Referral_Code,
	CAST(Referrer_Code  AS  STRING)  AS  Referrer_Code,
	CAST(Reject_Desc  AS  STRING)  AS  Reject_Desc,
	CAST(Residential_Add_Line_1  AS  STRING)  AS  Residential_Add_Line_1,
	CAST(Residential_Add_Line_2  AS  STRING)  AS  Residential_Add_Line_2,
	CAST(Residential_Add_Line_3  AS  STRING)  AS  Residential_Add_Line_3,
	CAST(Residential_Add_Line_4  AS  STRING)  AS  Residential_Add_Line_4,
	CAST(Residential_Phone_Country_Code  AS  STRING)  AS  Residential_Phone_Country_Code,
	CAST(Residential_Phone_Nbr  AS  STRING)  AS  Residential_Phone_Nbr,
	CAST(Session_Dte  AS  DATE)  AS  Session_Dte,
	CAST(Session_Time  AS  STRING)  AS  Session_Time,
	CAST(Signature_Ind  AS  STRING)  AS  Signature_Ind,
	CAST(Stmt_Type_Code  AS  STRING)  AS  Stmt_Type_Code,
	CAST(Submit_Time  AS  STRING)  AS  Submit_Time,
	CAST(Supp_Doc_Expiry_Dte  AS  DATE)  AS  Supp_Doc_Expiry_Dte,
	CAST(Supp_Doc_Nbr  AS  INT64)  AS  Supp_Doc_Nbr,
	CAST(Supp_Doc_Type_Code  AS  STRING)  AS  Supp_Doc_Type_Code,
	CAST(Supp_Issue_Country_Code  AS  STRING)  AS  Supp_Issue_Country_Code,
	CAST(TIN  AS  STRING)  AS  TIN,
	CAST(TIN_Declar_1  AS  STRING)  AS  TIN_Declar_1,
	CAST(TIN_Not_Provide_Reason_Code_1  AS  STRING)  AS  TIN_Not_Provide_Reason_Code_1,
	CAST(TIN_Unable_Obtain_Reason_Remark_1  AS  STRING)  AS  TIN_Unable_Obtain_Reason_Remark_1,
	CAST(TIN_2  AS  STRING)  AS  TIN_2,
	CAST(TIN_Declar_2  AS  STRING)  AS  TIN_Declar_2,
	CAST(TIN_Not_Provide_Reason_Code_2  AS  STRING)  AS  TIN_Not_Provide_Reason_Code_2,
	CAST(TIN_Unable_Obtain_Reason_Remark_2  AS  STRING)  AS  TIN_Unable_Obtain_Reason_Remark_2,
	CAST(TIN_3  AS  STRING)  AS  TIN_3,
	CAST(TIN_Declar_3  AS  STRING)  AS  TIN_Declar_3,
	CAST(TIN_Not_Provide_Reason_Code_3  AS  STRING)  AS  TIN_Not_Provide_Reason_Code_3,
	CAST(TIN_Unable_Obtain_Reason_Remark_3  AS  STRING)  AS  TIN_Unable_Obtain_Reason_Remark_3,
	CAST(TIN_4  AS  STRING)  AS  TIN_4,
	CAST(TIN_Declar_4  AS  STRING)  AS  TIN_Declar_4,
	CAST(TIN_Not_Provide_Reason_Code_4  AS  STRING)  AS  TIN_Not_Provide_Reason_Code_4,
	CAST(TIN_Unable_Obtain_Reason_Remark_4  AS  STRING)  AS  TIN_Unable_Obtain_Reason_Remark_4,
	CAST(TIN_5  AS  STRING)  AS  TIN_5,
	CAST(TIN_Declar_5  AS  STRING)  AS  TIN_Declar_5,
	CAST(TIN_Not_Provide_Reason_Code_5  AS  STRING)  AS  TIN_Not_Provide_Reason_Code_5,
	CAST(TIN_Unable_Obtain_Reason_Remark_5  AS  STRING)  AS  TIN_Unable_Obtain_Reason_Remark_5,
	CAST(Title_Desc  AS  STRING)  AS  Title_Desc,
	CAST(Vul_Cust_Q1  AS  STRING)  AS  Vul_Cust_Q1,
	CAST(Vul_Cust_Q2  AS  STRING)  AS  Vul_Cust_Q2,
	CAST(Vul_Cust_Q3  AS  STRING)  AS  Vul_Cust_Q3,
	CAST(Vul_Cust_Q4  AS  STRING)  AS  Vul_Cust_Q4,
	CAST(Vul_Cust_Q5  AS  STRING)  AS  Vul_Cust_Q5,
	CAST(Vul_Cust_Q6  AS  STRING)  AS  Vul_Cust_Q6,
	CAST(Vul_Cust_Q7  AS  STRING)  AS  Vul_Cust_Q7,
	CAST(Vul_Cust_Q8  AS  STRING)  AS  Vul_Cust_Q8
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	''  AS  __full_load_valid   
FROM  CTE_2 
)
 
SELECT  *  FROM  CTE_3
