WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-env-00.bqd_015_raw.OTHER_BANK_TRF_EVENT_raw 
),   
 
CTE_2  AS  ( 
SELECT
	CAST(column_name  AS  bigquery_type)  AS  column_name,
	CAST(Event_Id  AS  STRING)  AS  Event_Id,
	CAST(Applicant_Name  AS  STRING)  AS  Applicant_Name,
	CAST(Applicant_Place_of_Operation  AS  STRING)  AS  Applicant_Place_of_Operation,
	CAST(Applicant_Place_Of_Origin  AS  STRING)  AS  Applicant_Place_Of_Origin,
	CAST(Backdate_Ind  AS  STRING)  AS  Backdate_Ind,
	CAST(Bank_To_Bank_Info  AS  STRING)  AS  Bank_To_Bank_Info,
	CAST(BEA_China_Br_Code  AS  STRING)  AS  BEA_China_Br_Code,
	CAST(Ben_Acct_Nbr  AS  STRING)  AS  Ben_Acct_Nbr,
	CAST(Ben_Country_Code  AS  STRING)  AS  Ben_Country_Code,
	CAST(Ben_Instit_Country_Code  AS  STRING)  AS  Ben_Instit_Country_Code,
	CAST(Ben_Instit_Info  AS  STRING)  AS  Ben_Instit_Info,
	CAST(Ben_Instit_Name  AS  STRING)  AS  Ben_Instit_Name,
	CAST(Ben_Name  AS  STRING)  AS  Ben_Name,
	CAST(Ccy_Code  AS  STRING)  AS  Ccy_Code,
	CAST(Clearing_Bank_Code  AS  STRING)  AS  Clearing_Bank_Code,
	CAST(CNAPS_Ind  AS  STRING)  AS  CNAPS_Ind,
	CAST(CNH_Rate_Ind  AS  STRING)  AS  CNH_Rate_Ind,
	CAST(CNY_TT_Categ_Code  AS  STRING)  AS  CNY_TT_Categ_Code,
	CAST(CNY_TT_Trade_Ind  AS  STRING)  AS  CNY_TT_Trade_Ind,
	CAST(Covering_Bank_Code  AS  STRING)  AS  Covering_Bank_Code,
	CAST(Credit_Dte  AS  DATE)  AS  Credit_Dte,
	CAST(Eff_Dte  AS  DATE)  AS  Eff_Dte,
	CAST(Event_Amt  AS  NUMERIC)  AS  Event_Amt,
	CAST(Event_Amt_Hke  AS  NUMERIC)  AS  Event_Amt_Hke,
	CAST(Event_Rem  AS  STRING)  AS  Event_Rem,
	CAST(Event_Rem2  AS  STRING)  AS  Event_Rem2,
	CAST(Ext_Cust_Country_Code  AS  STRING)  AS  Ext_Cust_Country_Code,
	CAST(Ext_Cust_Info  AS  STRING)  AS  Ext_Cust_Info,
	CAST(FFM_Ovr_Id  AS  STRING)  AS  FFM_Ovr_Id,
	CAST(GCO_Waived_Ind  AS  STRING)  AS  GCO_Waived_Ind,
	CAST(HIT_Ind  AS  STRING)  AS  HIT_Ind,
	CAST(HKID_Resident_Ind  AS  STRING)  AS  HKID_Resident_Ind,
	CAST(HKL_Message_Ind  AS  STRING)  AS  HKL_Message_Ind,
	CAST(Instit_Country_Code  AS  STRING)  AS  Instit_Country_Code,
	CAST(Instit_Info  AS  STRING)  AS  Instit_Info,
	CAST(Instit_Info_Id  AS  STRING)  AS  Instit_Info_Id,
	CAST(Instit_Info_Rem  AS  STRING)  AS  Instit_Info_Rem,
	CAST(Inter_Bank_Country_Code  AS  STRING)  AS  Inter_Bank_Country_Code,
	CAST(Inter_Bank_Info  AS  STRING)  AS  Inter_Bank_Info,
	CAST(Msg_Type  AS  STRING)  AS  Msg_Type,
	CAST(MT191_Ind  AS  STRING)  AS  MT191_Ind,
	CAST(MT910_Ind  AS  STRING)  AS  MT910_Ind,
	CAST(Net_Pay_Amt  AS  NUMERIC)  AS  Net_Pay_Amt,
	CAST(Net_Pay_Ccy_Code  AS  STRING)  AS  Net_Pay_Ccy_Code,
	CAST(Net_Proceeds  AS  NUMERIC)  AS  Net_Proceeds,
	CAST(Net_Proceeds_Hke  AS  NUMERIC)  AS  Net_Proceeds_Hke,
	CAST(New_Fund_Ind  AS  STRING)  AS  New_Fund_Ind,
	CAST(Other_Bank_Acct_Nbr  AS  STRING)  AS  Other_Bank_Acct_Nbr,
	CAST(Paying_Bank_Code  AS  STRING)  AS  Paying_Bank_Code,
	CAST(Pmt_Code  AS  STRING)  AS  Pmt_Code,
	CAST(Pmt_Method_Code  AS  STRING)  AS  Pmt_Method_Code,
	CAST(POF_Remarks  AS  STRING)  AS  POF_Remarks,
	CAST(Purpose_Of_Fund  AS  STRING)  AS  Purpose_Of_Fund,
	CAST(Purpose_Of_Fund_Remarks  AS  STRING)  AS  Purpose_Of_Fund_Remarks,
	CAST(Purpose_Of_Pmt_BH  AS  STRING)  AS  Purpose_Of_Pmt_BH,
	CAST(Purpose_Of_Pmt_UAE  AS  STRING)  AS  Purpose_Of_Pmt_UAE,
	CAST(Receiver_Corr  AS  STRING)  AS  Receiver_Corr,
	CAST(Receiver_Corr_Bank_Id  AS  STRING)  AS  Receiver_Corr_Bank_Id,
	CAST(Reject_Reason_Code  AS  STRING)  AS  Reject_Reason_Code,
	CAST(Rel_to_Acct_Hldr  AS  STRING)  AS  Rel_to_Acct_Hldr,
	CAST(Rel_to_Acct_Hldr_Remarks  AS  STRING)  AS  Rel_to_Acct_Hldr_Remarks,
	CAST(Related_Acct_Nbr  AS  INT64)  AS  Related_Acct_Nbr,
	CAST(Related_Appl_Id  AS  STRING)  AS  Related_Appl_Id,
	CAST(Related_Control_Fields  AS  STRING)  AS  Related_Control_Fields,
	CAST(Return_Reason  AS  STRING)  AS  Return_Reason,
	CAST(Settle_Method  AS  STRING)  AS  Settle_Method,
	CAST(Sgold_Ind  AS  STRING)  AS  Sgold_Ind,
	CAST(SLA_Id  AS  STRING)  AS  SLA_Id,
	CAST(Source_Of_Fund  AS  STRING)  AS  Source_Of_Fund,
	CAST(Source_Of_Fund_Remarks  AS  STRING)  AS  Source_Of_Fund_Remarks,
	CAST(Stf_Nbr  AS  STRING)  AS  Stf_Nbr,
	CAST(Trade_Certified_Code  AS  STRING)  AS  Trade_Certified_Code,
	CAST(Trade_Ind  AS  STRING)  AS  Trade_Ind,
	CAST(Treasury_Ref  AS  STRING)  AS  Treasury_Ref,
	CAST(UETR  AS  STRING)  AS  UETR,
	CAST(Ultimate_Instit_Country_Code  AS  STRING)  AS  Ultimate_Instit_Country_Code,
	CAST(Ultimate_Instit_Info  AS  STRING)  AS  Ultimate_Instit_Info,
	CAST(Ultimate_Instit_Info_Id  AS  STRING)  AS  Ultimate_Instit_Info_Id
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	''  AS  __full_load_valid   
FROM  CTE_2 
)
 
SELECT  *  FROM  CTE_3
