CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_party_add_raw`  (
Add_Contact_Id  STRING(3),
Add_Use_Code  STRING(3),
Doc_Nbr  STRING(25),
Doc_Type_Code  STRING(2),
Issue_Country_Code  STRING(2),
Add_Line_1  STRING(45),
Add_Line_2  STRING(45),
Add_Line_3  STRING(45),
Add_Line_4  STRING(45),
Add_Line_5  STRING(45),
Country_Code  STRING(2),
Ctry_Val  STRING(3),
Ctry_Val_Update_Ctr_Id  STRING(4),
Ctry_Val_Update_Dte  STRING(8),
Ctry_Val_Update_Offr_Id  STRING(8),
District_Code  STRING(6),
Last_Update_Dte  STRING(8),
Permanent_Add_Ind  STRING(1),
Postal_Code  STRING(30),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
