CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_party_acct_raw`  (
Acct_Nbr  STRING(20),
Acct_Party_Role_Code  STRING(3),
Acct_Party_Start_Dte  STRING(4),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Doc_Nbr  STRING(25),
Doc_Type_Code  STRING(2),
Issue_Country_Code  STRING(2),
Acct_Party_End_Dte  STRING(4),
Aloc_Pct  STRING(4),
Appl_Code  STRING(3),
Create_By_Offr_Id  STRING(24),
Guarantor_Limit_Hke  STRING(8),
Primary_Owner_Ind  STRING(1),
Acct_Party_Role_Seq  STRING(4),
Rel_Setup_By_Offr_Id  STRING(8),
Stmt_Type_Code  STRING(1),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
