CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_irn_raq_raw`  (
Doc_Type_Code  STRING(10),
Doc_Nbr  STRING(25),
Issue_Country_Code  STRING(2),
Sign_Dte  STRING(4),
Sign_Time  STRING(4),
Blind_Ind  STRING(3),
Br_Code  STRING(15),
Create_By_Offr_Id  STRING(20),
Display_Risk_Lvl  STRING(10),
Dte_Of_Birth_Incorporation  STRING(4),
Education_Lvl  STRING(3),
Impaired_Ind  STRING(3),
Mthly_Income  STRING(3),
Quest_Ans  STRING(50),
Quest_ID  STRING(19),
Quest_Type  STRING(10),
RAQ_Chnl  STRING(20),
Real_Risk_Lvl  STRING(10),
Risk_Status  STRING(1),
Risk_Tolerance_Lvl  STRING(10),
Total_Asset  STRING(3),
Version  STRING(3),
First_Vul_Cust  STRING(1),
Final_Vul_Cust  STRING(1),
Disagree_Flag  STRING(1),
Disagree_Reason  STRING(60),
Observe_Impaired_Ind  STRING(1),
Party_Intl_Nbr  STRING(8),
Trx_Linked_Ref  STRING(18),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
