CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_custodian_acct_portfolio_dtl_raw`  (
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Start_Dte  STRING(4),
End_Dte  STRING(4),
ISIN_Code  STRING(12),
Qty  STRING(8),
Stock_Name  STRING(40),
Share_Type_Code  STRING(2),
Share_Type_Desc  STRING(20),
Share_Nature_Code  STRING(2),
Share_Nature_Desc  STRING(5),
Unit_Price  STRING(8),
Ccy_code  STRING(3),
Portfolio_Market_Val  STRING(8),
Portfolio_Market_Val_Hke  STRING(8),
Coupon_Rate  STRING(4),
Maturity_Dte  STRING(4),
Order_Code  STRING(8),
Stock_Code  STRING(5),
Portfolio_Type_Code  STRING(2),
Cbs_Prod_Code  STRING(4),
Qty_Being_Held  STRING(8),
Price_Dte  STRING(4),
Share_Sub_Type_Code  STRING(5),
Share_Sub_Type_Desc  STRING(40),
Prod_Risk_Rating  STRING(1),
Issuer_Code  STRING(5),
Issuer_Name  STRING(80),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
