CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_lrs_tagging_raw`  (
Batch_Dte  STRING(8),
Tag_Entity_Id  STRING(36),
Seq_Nbr  STRING(11),
Actv_Type  STRING(13),
Curr_Page  STRING(13),
Device_Model1  STRING(1024),
Device_Model2  STRING(15),
Device_OS_Ver  STRING(10),
Input_Field_Time_Spent  STRING(20),
Is_Horizontal_Ind  STRING(1),
Mall_User_Id1  STRING(36),
Mall_User_Id2  STRING(26),
Prev_Page  STRING(13),
Scroll_Depth_X_Start  STRING(13),
Scroll_Depth_X_End  STRING(13),
Scroll_Depth_Y_Start  STRING(13),
Scroll_Depth_Y_End  STRING(13),
Session_Id  STRING(32),
Tag_Event_Timestamp  STRING(20),
Tag_Name  STRING(13),
UUID1  STRING(1024),
UUID2  STRING(26),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
