CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_fin_event_raw`  (
Event_Id  STRING(23),
Chq_Nbr  STRING(13),
Cr_Dr_Ind  STRING(1),
Event_Amt  STRING(16),
Event_Amt_Hke  STRING(16),
Event_Amt_Media_Code  STRING(3),
Event_Categ_Code  STRING(4),
Event_Ccy_Code  STRING(3),
Event_Country_Code  STRING(2),
Event_Ex_Rate  STRING(8),
Fin_Event_Comment  STRING(200),
Mrch_Id  STRING(5),
Override_Ind  STRING(1),
Val_Dte  STRING(4),
Trx_Nbr  STRING(9),
Source_Of_Fund  STRING(1),
Purpose_Of_Fund  STRING(1),
Rel_to_Acct_Hldr  STRING(1),
POF_Remarks  STRING(50),
MSOF_Ref  STRING(8),
Trx_Linked_Ref  STRING(18),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
