CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_consumer_event_raw`  (
Event_Id  STRING(23),
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Campaign_Event_Id  STRING(8),
CBS_Orig_Chnl  STRING(3),
Chnl_Id  STRING(14),
Chnl_Type_Code  STRING(3),
Control_Fields  STRING(8),
Event_Actv_Type_Code  STRING(7),
Event_Categ_Code  STRING(3),
Event_Dte  STRING(8),
Event_Status_Code  STRING(3),
Event_Status_Reason_Code  STRING(8),
Event_Time  STRING(6),
Fin_Ind  STRING(1),
Instr_Nbr  STRING(17),
Ref_Nbr  STRING(30),
Self_Srv_Ind  STRING(1),
Source_Trx_Ref_Nbr  STRING(25),
Third_Party_Ind  STRING(1),
Two_FA_Type  STRING(1),
User_Id  STRING(8),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
