CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_fps_event_raw`  (
Event_Id  STRING(40),
Bill_Nbr  STRING(35),
Message_Id  STRING(35),
Pmt_Categ_Purpose_Code  STRING(6),
Pmt_Method_Code  STRING(2),
Correspondent_Proxy_Id_Type  STRING(4),
Correspondent_Proxy_Id  STRING(34),
Related_Proxy_Id_Type  STRING(4),
Related_Proxy_Id  STRING(35),
Related_Bk_Code  STRING(35),
Related_Acct_Nbr  STRING(35),
Related_Cust_Name  STRING(140),
Business_Service_Code  STRING(35),
Cust_Ref  STRING(140),
Mandate_Id  STRING(35),
FPS_Ref_Nbr  STRING(35),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
