CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_cur_acct_raw`  (
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Base_Rate_Loading  STRING(4),
Chq_Book_Enable_Ind  STRING(1),
Limit_Status_Code  STRING(2),
Od_Limit_Amt  STRING(8),
Down_Grade_Dte  STRING(4),
Last_xxx_Od_Start_Dte  STRING(4),
Od_Limit_Close_Dte  STRING(4),
Od_Limit_Open_Dte  STRING(4),
Review_Dte  STRING(4),
Cancel_Code  STRING(2),
Closing_Bal_Amt  STRING(8),
Int_Suspend_Ind  STRING(2),
Int_Suspend_Dte  STRING(4),
Last_Review_Dte  STRING(4),
Min_Pay_Waive_Ind  STRING(1),
Next_Review_Dte  STRING(4),
Od_Acct_Type  STRING(2),
Od_Limit_Suspend_Dte  STRING(4),
Special_Remark_Code  STRING(2),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
