CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_cr_card_acct_cycle_raw`  (
Acct_Nbr  STRING(16),
Appl_Id  STRING(3),
Control_Fields  STRING(4),
Cycle_Dte  STRING(8),
Anl_Fee_Amt  STRING(15),
Anl_Fee_Reversal_Amt  STRING(15),
Cash_Advance_Amt  STRING(15),
Cash_Advance_Cnt  STRING(8),
Cash_Advance_Fee_Amt  STRING(15),
Cash_Advance_Fee_Reversal_Amt  STRING(15),
Cash_Advance_Reversal_Amt  STRING(15),
Cash_Advance_Reversal_Cnt  STRING(8),
Cur_Due_Amt  STRING(15),
Delq_Code  STRING(1),
Fin_Chrg_Amt  STRING(15),
IBNP_Cash_Amt  STRING(13),
IBNP_Retail_Amt  STRING(13),
Late_Fee_Amt  STRING(15),
Late_Fee_Reversal_Amt  STRING(15),
Pmt_Amt  STRING(15),
Pmt_Cnt  STRING(8),
Pmt_Pct_Code  STRING(1),
Pmt_Reversal_Amt  STRING(15),
Pmt_Reversal_Cnt  STRING(8),
Retail_Amt  STRING(15),
Retail_Cnt  STRING(8),
Retail_Reversal_Amt  STRING(15),
Retail_Reversal_Cnt  STRING(8),
Stmt_Bal  STRING(15),
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__file_name  STRING,   
__load_type  STRING,   
__sys_code  STRING,   
__row_number  STRING 
);
