CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_other_fx_event_raw`  (
Event_Id  STRING(23),
Applicant_Add  STRING(136),
Applicant_Phone_Nbr  STRING(9),
Bank_Buy_Amt  STRING(15),
Bank_Buy_Ccy_Code  STRING(3),
Bank_Sell_Amt  STRING(15),
Bank_Sell_Ccy_Code  STRING(3),
Ccy_Pair  STRING(7),
CNH_Rate_Ind  STRING(1),
Comm_Rate  STRING(12),
Counter_Rate  STRING(12),
Doc_Nbr  STRING(25),
Doc_Type_Code  STRING(2),
Event_Amt  STRING(15),
Event_Amt_Hke  STRING(15),
Event_Ccy_Code  STRING(3),
Issue_Country_Code  STRING(2),
Party_Name  STRING(80),
Payee_Name  STRING(240),
Pmt_Method_Code  STRING(1),
POF_Remarks  STRING(25),
Purpose_Of_Fund  STRING(1),
Rel_to_Acct_Hldr  STRING(1),
Related_Acct_Nbr  STRING(20),
Related_Appl_Id  STRING(3),
Related_Control_Fields  STRING(8),
Source_Of_Fund  STRING(1),
Special_Rate  STRING(12),
Treasury_Ref  STRING(7),
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__file_name  STRING,   
__load_type  STRING,   
__sys_code  STRING,   
__row_number  STRING 
);
