CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_cim_upl_campaign_raw`  (
Batch_Dte  STRING(8),
Oper_Code  STRING(1),
Campaign_Id  STRING(8),
Update_By  STRING(20),
Campaign_Desc  STRING(150),
Campaign_Objective  STRING(240),
Campaign_Start_Dte  STRING(8),
Campaign_End_Dte  STRING(8),
Global_Exclude_Check_Ind  STRING(1),
No_Acct_Check_Ind  STRING(1),
Optout_Check_Ind  STRING(1),
Prod_Type_Code  STRING(4),
Chnl_Type_Code  STRING(4),
Recency_Check_Ind  STRING(1),
Update_Dte  STRING(8),
Update_Time  STRING(8),
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__file_name  STRING,   
__load_type  STRING,   
__sys_code  STRING,   
__row_number  STRING 
);
