CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_cur_acct_raw`  (
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Cancel_Code  STRING(2),
Chq_Book_Enable_Ind  STRING(1),
Closing_Bal_Amt  STRING(17),
Int_Suspend_Dte  STRING(8),
Int_Suspend_Ind  STRING(2),
Last_Review_Dte  STRING(8),
Limit_Status_Code  STRING(2),
Min_Pay_Waive_Ind  STRING(1),
Next_Review_Dte  STRING(8),
Od_Acct_Type  STRING(2),
Od_Limit_Amt  STRING(11),
Od_Limit_Close_Dte  STRING(8),
Od_Limit_Open_Dte  STRING(8),
Od_Limit_Suspend_Dte  STRING(8),
Special_Remark_Code  STRING(2),
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__file_name  STRING,   
__load_type  STRING,   
__sys_code  STRING,   
__row_number  STRING 
);
