CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_cr_line_raw`  (
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Create_Dte  STRING(8),
Anl_Fee_Recv_Ind  STRING(1),
Arrangement_Fee  STRING(15),
Auto_Suspend_Dte  STRING(8),
Cancel_Code  STRING(2),
Cash_Rebate_End_Dte  STRING(8),
Closing_Bal_Amt  STRING(15),
Cr_Line_Close_Dte  STRING(8),
Down_Grade_Dte  STRING(8),
Down_Status_Dte  STRING(8),
Group_Nbr  STRING(5),
Group_Nbr_Chng_Dte  STRING(8),
Int_Rebate_End_Dte  STRING(8),
Last_Review_Dte  STRING(8),
Limit_Status_Code  STRING(2),
Min_Pay_Waive_Ind  STRING(2),
Next_Review_Dte  STRING(8),
Privilage_Int_Rate_End_Dte  STRING(8),
Privilage_Int_Rate_Ind  STRING(1),
Repayment_Fee_Waive_Ind  STRING(1),
Repmt_In_Arrears_Amt  STRING(15),
Review_Code  STRING(2),
Suspend_Code  STRING(2),
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__file_name  STRING,   
__load_type  STRING,   
__sys_code  STRING,   
__row_number  STRING 
);
