CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_campaign_response_history_raw`  (
Batch_Dte  STRING(8),
Doc_Nbr  STRING(25),
Doc_Type_Code  STRING(2),
Issue_Country_Code  STRING(2),
Party_Type  STRING(1),
Campaign_Id  STRING(8),
Version_Id  STRING(11),
Selection_Dte  STRING(8),
Cell_Id  STRING(11),
Step_Id  STRING(11),
This_step_Dte  STRING(8),
Campaign_Class  STRING(10),
Party_Intl_Nbr  STRING(8),
Response_Dte  STRING(8),
Response_Time  STRING(11),
Response_Code  STRING(4),
Call_Back_Dte  STRING(8),
Complaint_Code  STRING(5),
Complaint_Txt  STRING(100),
More_Info_Code  STRING(5),
More_Info_Txt  STRING(100),
Retry_Count  STRING(2),
User_Data_Code  STRING(5),
User_Data_Txt  STRING(100),
Agent_Id  STRING(20),
Call_Back_Time  STRING(6),
Call_Back_Phone  STRING(20),
Cim_Call_Back_Dte  STRING(8),
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__file_name  STRING,   
__load_type  STRING,   
__sys_code  STRING,   
__row_number  STRING 
);
