CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_custodian_acct_portfolio_dtl_raw`  (
Acct_Nbr  STRING(16),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Start_Dte  STRING(8),
Stock_Code  STRING(5),
Cbs_Prod_Code  STRING(4),
Ccy_Code  STRING(3),
Coupon_Rate  STRING(5),
End_Dte  STRING(8),
ISIN_Code  STRING(12),
Issuer_Code  STRING(5),
Issuer_Name  STRING(80),
Maturity_Dte  STRING(8),
Old_Share_Type_Code  STRING(2),
Order_Code  STRING(8),
Portfolio_Market_Val  STRING(13),
Portfolio_Market_Val_Hke  STRING(13),
Price_Dte  STRING(8),
Prod_Risk_Rating  STRING(1),
Qty  STRING(15),
Qty_Being_Held  STRING(15),
Share_Nature_Code  STRING(2),
Share_Nature_Desc  STRING(5),
Share_Sub_Type_Code  STRING(5),
Share_Sub_Type_Desc  STRING(40),
Share_Type_Code  STRING(2),
Share_Type_Desc  STRING(20),
Stock_Name  STRING(40),
Unit_Price  STRING(13),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
