version: 2
models:
  - name: Prod_Type
    schema: bqd_995_marts
    columns:
    - name: Prod_Type_Code
      policy_tags:
        - '{{ env_var("PT_TAXONOMY", var("DEFAULT_PT_TAXONOMY")) ~ env_var("PT_Internal", var("DEFAULT_PT_Internal")) }}'
    - name: Prod_Type_Desc
      policy_tags:
        - '{{ env_var("PT_TAXONOMY", var("DEFAULT_PT_TAXONOMY")) ~ env_var("PT_Internal", var("DEFAULT_PT_Internal")) }}'