WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-dev-00.bqd_015_raw.tag_collat_ppty_info_raw 
),   
 
CTE_2  AS  ( 
SELECT
	SAFE_CAST(Acct_Nbr  AS  INT64)  AS  Acct_Nbr,
	SAFE_CAST(Appl_Id  AS  STRING)  AS  Appl_Id,
	SAFE_CAST(Control_Fields  AS  STRING)  AS  Control_Fields,
	SAFE_CAST(Actual_Area  AS  NUMERIC)  AS  Actual_Area,
	SAFE_CAST(Already_Own_Ind  AS  STRING)  AS  Already_Own_Ind,
	SAFE_CAST(Appurtenance  AS  STRING)  AS  Appurtenance,
	SAFE_CAST(Area_Unit  AS  STRING)  AS  Area_Unit,
	SAFE_CAST(Bldg_Name  AS  STRING)  AS  Bldg_Name,
	SAFE_CAST(Chrg_Code_Chng_Dte  AS  DATE)  AS  Chrg_Code_Chng_Dte,
	SAFE_CAST(Chrg_Code  AS  STRING)  AS  Chrg_Code,
	SAFE_CAST(Cmple_Dte  AS  DATE)  AS  Cmple_Dte,
	SAFE_CAST(Collat_Class_Code  AS  STRING)  AS  Collat_Class_Code,
	SAFE_CAST(Collat_Class_Type_Code  AS  STRING)  AS  Collat_Class_Type_Code,
	SAFE_CAST(Constr_Area  AS  NUMERIC)  AS  Constr_Area,
	SAFE_CAST(Est_Val  AS  NUMERIC)  AS  Est_Val,
	SAFE_CAST(Est_Val_Appraiser  AS  STRING)  AS  Est_Val_Appraiser,
	SAFE_CAST(Est_Val_Ccy_Code  AS  STRING)  AS  Est_Val_Ccy_Code,
	SAFE_CAST(Est_Val_Dte  AS  DATE)  AS  Est_Val_Dte,
	SAFE_CAST(Estate_Type_Code  AS  STRING)  AS  Estate_Type_Code,
	SAFE_CAST(Foresale_Val_Amt  AS  NUMERIC)  AS  Foresale_Val_Amt,
	SAFE_CAST(Foresale_Val_Ccy_Code  AS  STRING)  AS  Foresale_Val_Ccy_Code,
	SAFE_CAST(Foresale_Val_Dte  AS  DATE)  AS  Foresale_Val_Dte,
	SAFE_CAST(GHOS_Court_Nbr  AS  STRING)  AS  GHOS_Court_Nbr,
	SAFE_CAST(GHOS_Phase_Code  AS  STRING)  AS  GHOS_Phase_Code,
	SAFE_CAST(HKMC_Valuation_Amt  AS  NUMERIC)  AS  HKMC_Valuation_Amt,
	SAFE_CAST(HKMC_Valuation_Ccy_Code  AS  STRING)  AS  HKMC_Valuation_Ccy_Code,
	SAFE_CAST(HKMC_Valuation_Dte  AS  DATE)  AS  HKMC_Valuation_Dte,
	SAFE_CAST(House_Type_Code  AS  STRING)  AS  House_Type_Code,
	SAFE_CAST(Incentive_Amt  AS  NUMERIC)  AS  Incentive_Amt,
	SAFE_CAST(Incentive_Ccy_Code  AS  STRING)  AS  Incentive_Ccy_Code,
	SAFE_CAST(Lease_Term  AS  NUMERIC)  AS  Lease_Term,
	SAFE_CAST(Lease_Term_Comm_Dte  AS  DATE)  AS  Lease_Term_Comm_Dte,
	SAFE_CAST(Lot_Remark  AS  STRING)  AS  Lot_Remark,
	SAFE_CAST(Market_Type_Code  AS  STRING)  AS  Market_Type_Code,
	SAFE_CAST(Net_Realz_Val_Amt  AS  NUMERIC)  AS  Net_Realz_Val_Amt,
	SAFE_CAST(Net_Realz_Val_Ccy_Code  AS  STRING)  AS  Net_Realz_Val_Ccy_Code,
	SAFE_CAST(Net_Realz_Val_Dte  AS  DATE)  AS  Net_Realz_Val_Dte,
	SAFE_CAST(Net_Realz_Val_Pct  AS  NUMERIC)  AS  Net_Realz_Val_Pct,
	SAFE_CAST(New_Property_Ind  AS  STRING)  AS  New_Property_Ind,
	SAFE_CAST(Occup_Permit_Dte  AS  DATE)  AS  Occup_Permit_Dte,
	SAFE_CAST(Occup_Permit_Cmple_Dte  AS  DATE)  AS  Occup_Permit_Cmple_Dte,
	SAFE_CAST(Orig_Val  AS  NUMERIC)  AS  Orig_Val,
	SAFE_CAST(Orig_Val_Ccy_Code  AS  STRING)  AS  Orig_Val_Ccy_Code,
	SAFE_CAST(Portfolio_Val  AS  NUMERIC)  AS  Portfolio_Val,
	SAFE_CAST(Portfolio_Val_Ccy_Code  AS  STRING)  AS  Portfolio_Val_Ccy_Code,
	SAFE_CAST(Portfolio_Val_Dte  AS  DATE)  AS  Portfolio_Val_Dte,
	SAFE_CAST(Ppty_Country_Code  AS  STRING)  AS  Ppty_Country_Code,
	SAFE_CAST(Ppty_District_Code  AS  STRING)  AS  Ppty_District_Code,
	SAFE_CAST(Ppty_Location  AS  STRING)  AS  Ppty_Location,
	SAFE_CAST(Ppty_Status  AS  STRING)  AS  Ppty_Status,
	SAFE_CAST(Ppty_Type_Code  AS  STRING)  AS  Ppty_Type_Code,
	SAFE_CAST(Prem_Liab_Pct  AS  NUMERIC)  AS  Prem_Liab_Pct,
	SAFE_CAST(Project_Code  AS  STRING)  AS  Project_Code,
	SAFE_CAST(Purchase_Amt  AS  NUMERIC)  AS  Purchase_Amt,
	SAFE_CAST(Purchase_Amt_Ccy_Code  AS  STRING)  AS  Purchase_Amt_Ccy_Code,
	SAFE_CAST(Purchase_Dte  AS  DATE)  AS  Purchase_Dte,
	SAFE_CAST(Reconstruct_Ccy_Code  AS  STRING)  AS  Reconstruct_Ccy_Code,
	SAFE_CAST(Reconstruct_Val  AS  NUMERIC)  AS  Reconstruct_Val,
	SAFE_CAST(Reconstruct_Val_Appraiser  AS  STRING)  AS  Reconstruct_Val_Appraiser,
	SAFE_CAST(Reconstruct_Val_Dte  AS  DATE)  AS  Reconstruct_Val_Dte,
	SAFE_CAST(Rental_Assign_Ind  AS  STRING)  AS  Rental_Assign_Ind,
	SAFE_CAST(Solicitor_Code  AS  STRING)  AS  Solicitor_Code,
	SAFE_CAST(UnderTaking_Type_Code  AS  STRING)  AS  UnderTaking_Type_Code,
	SAFE_CAST(Usage_Code  AS  STRING)  AS  Usage_Code,
	SAFE_CAST(Valuation_Fee_Amt  AS  NUMERIC)  AS  Valuation_Fee_Amt,
	SAFE_CAST(Valuation_Fee_Ccy_Code  AS  STRING)  AS  Valuation_Fee_Ccy_Code
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_01YN('Already_Own_Ind')}},
	{{validate_NoFutureDate('Chrg_Code_Chng_Dte')}},
	{{validate_NoFutureDate('Cmple_Dte')}},
	{{validate_Future_Date('Est_Val_Dte')}},
	{{validate_NoFutureDate('Foresale_Val_Dte')}},
	{{validate_NoFutureDate('HKMC_Valuation_Dte')}},
	{{validate_NoFutureDate('Lease_Term_Comm_Dte')}},
	{{validate_Future_Date('Net_Realz_Val_Dte')}},
	{{validate_01YN('New_Property_Ind')}},
	{{validate_NoFutureDate('Occup_Permit_Dte')}},
	{{validate_Future_Date('Portfolio_Val_Dte')}},
	{{validate_CountryCode('Ppty_Country_Code')}},
	{{validate_NoFutureDate('Purchase_Dte')}},
	{{validate_NoFutureDate('Reconstruct_Val_Dte')}},
	{{validate_01YN('Rental_Assign_Ind')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
	Acct_Nbr,
	Appl_Id,
	Control_Fields,
	Actual_Area,
	Already_Own_Ind,
	Appurtenance,
	Area_Unit,
	Bldg_Name,
	Chrg_Code_Chng_Dte,
	Chrg_Code,
	Cmple_Dte,
	Collat_Class_Code,
	Collat_Class_Type_Code,
	Constr_Area,
	Est_Val,
	Est_Val_Appraiser,
	Est_Val_Ccy_Code,
	Est_Val_Dte,
	Estate_Type_Code,
	Foresale_Val_Amt,
	Foresale_Val_Ccy_Code,
	Foresale_Val_Dte,
	GHOS_Court_Nbr,
	GHOS_Phase_Code,
	HKMC_Valuation_Amt,
	HKMC_Valuation_Ccy_Code,
	HKMC_Valuation_Dte,
	House_Type_Code,
	Incentive_Amt,
	Incentive_Ccy_Code,
	Lease_Term,
	Lease_Term_Comm_Dte,
	Lot_Remark,
	Market_Type_Code,
	Net_Realz_Val_Amt,
	Net_Realz_Val_Ccy_Code,
	Net_Realz_Val_Dte,
	Net_Realz_Val_Pct,
	New_Property_Ind,
	Occup_Permit_Dte,
	Occup_Permit_Cmple_Dte,
	Orig_Val,
	Orig_Val_Ccy_Code,
	Portfolio_Val,
	Portfolio_Val_Ccy_Code,
	Portfolio_Val_Dte,
	Ppty_Country_Code,
	Ppty_District_Code,
	Ppty_Location,
	Ppty_Status,
	Ppty_Type_Code,
	Prem_Liab_Pct,
	Project_Code,
	Purchase_Amt,
	Purchase_Amt_Ccy_Code,
	Purchase_Dte,
	Reconstruct_Ccy_Code,
	Reconstruct_Val,
	Reconstruct_Val_Appraiser,
	Reconstruct_Val_Dte,
	Rental_Assign_Ind,
	Solicitor_Code,
	UnderTaking_Type_Code,
	Usage_Code,
	Valuation_Fee_Amt,
	Valuation_Fee_Ccy_Code,
	{{  full_valid_flag(['__01YN_valid_Already_Own_Ind','__NoFutureDate_valid_Chrg_Code_Chng_Dte','__NoFutureDate_valid_Cmple_Dte','__Future_Date_valid_Est_Val_Dte','__NoFutureDate_valid_Foresale_Val_Dte','__NoFutureDate_valid_HKMC_Valuation_Dte','__NoFutureDate_valid_Lease_Term_Comm_Dte','__Future_Date_valid_Net_Realz_Val_Dte','__01YN_valid_New_Property_Ind','__NoFutureDate_valid_Occup_Permit_Dte','__Future_Date_valid_Portfolio_Val_Dte','__CountryCode_valid_Ppty_Country_Code','__NoFutureDate_valid_Purchase_Dte','__NoFutureDate_valid_Reconstruct_Val_Dte','__01YN_valid_Rental_Assign_Ind'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
