WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-dev-00.bqd_015_raw.tag_ln_acct_raw 
),   
 
CTE_2  AS  ( 
SELECT
	SAFE_CAST(Acct_Nbr  AS  INT64)  AS  Acct_Nbr,
	SAFE_CAST(Appl_Id  AS  STRING)  AS  Appl_Id,
	SAFE_CAST(Control_Fields  AS  STRING)  AS  Control_Fields,
	SAFE_CAST(Accum_Waived_Od_Int  AS  NUMERIC)  AS  Accum_Waived_Od_Int,
	SAFE_CAST(Appl_Appl_Id  AS  STRING)  AS  Appl_Appl_Id,
	SAFE_CAST(Appl_Control_Fields  AS  STRING)  AS  Appl_Control_Fields,
	SAFE_CAST(Appl_Nbr  AS  STRING)  AS  Appl_Nbr,
	SAFE_CAST(Appl_Ppsl_Seq_Nbr  AS  NUMERIC)  AS  Appl_Ppsl_Seq_Nbr,
	SAFE_CAST(Agency_Code  AS  STRING)  AS  Agency_Code,
	SAFE_CAST(Bk_Return_Code  AS  STRING)  AS  Bk_Return_Code,
	SAFE_CAST(Debt_Status  AS  STRING)  AS  Debt_Status,
	SAFE_CAST(Facility_Code  AS  STRING)  AS  Facility_Code,
	SAFE_CAST(Gov_Guarantee_Pct  AS  NUMERIC)  AS  Gov_Guarantee_Pct,
	SAFE_CAST(Impair_Ln_Ind  AS  STRING)  AS  Impair_Ln_Ind,
	SAFE_CAST(Insl_Freq_Nbr_Unit  AS  NUMERIC)  AS  Insl_Freq_Nbr_Unit,
	SAFE_CAST(Insl_Freq_Unit_Type_Code  AS  STRING)  AS  Insl_Freq_Unit_Type_Code,
	SAFE_CAST(Int_Base_Rate  AS  NUMERIC)  AS  Int_Base_Rate,
	SAFE_CAST(Int_Start_Dte  AS  DATE)  AS  Int_Start_Dte,
	SAFE_CAST(Int_Rate_Adj_Pct  AS  NUMERIC)  AS  Int_Rate_Adj_Pct,
	SAFE_CAST(Int_Rate_Base_Code  AS  STRING)  AS  Int_Rate_Base_Code,
	SAFE_CAST(Int_Rate_Code  AS  STRING)  AS  Int_Rate_Code,
	SAFE_CAST(Int_Rate_Loading  AS  NUMERIC)  AS  Int_Rate_Loading,
	SAFE_CAST(Int_Rate_Mode  AS  STRING)  AS  Int_Rate_Mode,
	SAFE_CAST(Int_Rate_Tot  AS  NUMERIC)  AS  Int_Rate_Tot,
	SAFE_CAST(Int_Rate_Type  AS  STRING)  AS  Int_Rate_Type,
	SAFE_CAST(Last_Rate_Chng_Dte  AS  DATE)  AS  Last_Rate_Chng_Dte,
	SAFE_CAST(Last_Settle_Dte  AS  DATE)  AS  Last_Settle_Dte,
	SAFE_CAST(Ln_Introducer_Code  AS  STRING)  AS  Ln_Introducer_Code,
	SAFE_CAST(Ln_Seq_Nbr  AS  NUMERIC)  AS  Ln_Seq_Nbr,
	SAFE_CAST(Ln_Type_Code  AS  STRING)  AS  Ln_Type_Code,
	SAFE_CAST(Ln_Use_Country  AS  STRING)  AS  Ln_Use_Country,
	SAFE_CAST(Maturity_Dte  AS  DATE)  AS  Maturity_Dte,
	SAFE_CAST(Mortgage_Plan_Code  AS  STRING)  AS  Mortgage_Plan_Code,
	SAFE_CAST(Repmt_Type_Code  AS  STRING)  AS  Repmt_Type_Code,
	SAFE_CAST(Next_Pmt_Due_Dte  AS  DATE)  AS  Next_Pmt_Due_Dte,
	SAFE_CAST(Od_Fixed_Int_Ind  AS  STRING)  AS  Od_Fixed_Int_Ind,
	SAFE_CAST(Od_Grace_Period  AS  NUMERIC)  AS  Od_Grace_Period,
	SAFE_CAST(Od_Int_Adj_Pct  AS  NUMERIC)  AS  Od_Int_Adj_Pct,
	SAFE_CAST(Od_Int_Amt  AS  NUMERIC)  AS  Od_Int_Amt,
	SAFE_CAST(Od_Int_Rate  AS  NUMERIC)  AS  Od_Int_Rate,
	SAFE_CAST(Od_Prin_Amt  AS  NUMERIC)  AS  Od_Prin_Amt,
	SAFE_CAST(Od_Rate_Chng_Opt  AS  STRING)  AS  Od_Rate_Chng_Opt,
	SAFE_CAST(Od_Rate_Type  AS  STRING)  AS  Od_Rate_Type,
	SAFE_CAST(Orig_Ln_Amt  AS  NUMERIC)  AS  Orig_Ln_Amt,
	SAFE_CAST(OS_Od_Int_Amt  AS  NUMERIC)  AS  OS_Od_Int_Amt,
	SAFE_CAST(Os_Prin_Amt  AS  NUMERIC)  AS  Os_Prin_Amt,
	SAFE_CAST(Pmt_Due_Dte  AS  DATE)  AS  Pmt_Due_Dte,
	SAFE_CAST(Ppsl_Dte  AS  DATE)  AS  Ppsl_Dte,
	SAFE_CAST(Prod_Code  AS  STRING)  AS  Prod_Code,
	SAFE_CAST(Project_Code  AS  STRING)  AS  Project_Code,
	SAFE_CAST(Promote_Code  AS  STRING)  AS  Promote_Code,
	SAFE_CAST(Purpose_Of_Fin_HKMA  AS  STRING)  AS  Purpose_Of_Fin_HKMA,
	SAFE_CAST(Rate_Chng_Eff_Dte  AS  DATE)  AS  Rate_Chng_Eff_Dte,
	SAFE_CAST(Rate_Chng_Opt  AS  STRING)  AS  Rate_Chng_Opt,
	SAFE_CAST(Repmt_Method_Code  AS  STRING)  AS  Repmt_Method_Code,
	SAFE_CAST(Reprice_Option  AS  STRING)  AS  Reprice_Option,
	SAFE_CAST(Solicitor_Code  AS  STRING)  AS  Solicitor_Code,
	SAFE_CAST(Tenor  AS  NUMERIC)  AS  Tenor,
	SAFE_CAST(Written_Off_Amt  AS  NUMERIC)  AS  Written_Off_Amt,
	SAFE_CAST(Written_Off_Dte  AS  DATE)  AS  Written_Off_Dte
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_NoFutureDate('Int_Start_Dte')}},
	{{validate_NoFutureDate('Last_Rate_Chng_Dte')}},
	{{validate_NoFutureDate('Last_Settle_Dte')}},
	{{validate_Future_Date('Maturity_Dte')}},
	{{validate_Future_Date('Pmt_Due_Dte')}},
	{{validate_Future_Date('Ppsl_Dte')}},
	{{validate_NoFutureDate('Rate_Chng_Eff_Dte')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
	Acct_Nbr,
	Appl_Id,
	Control_Fields,
	Accum_Waived_Od_Int,
	Appl_Appl_Id,
	Appl_Control_Fields,
	Appl_Nbr,
	Appl_Ppsl_Seq_Nbr,
	Agency_Code,
	Bk_Return_Code,
	Debt_Status,
	Facility_Code,
	Gov_Guarantee_Pct,
	Impair_Ln_Ind,
	Insl_Freq_Nbr_Unit,
	Insl_Freq_Unit_Type_Code,
	Int_Base_Rate,
	Int_Start_Dte,
	Int_Rate_Adj_Pct,
	Int_Rate_Base_Code,
	Int_Rate_Code,
	Int_Rate_Loading,
	Int_Rate_Mode,
	Int_Rate_Tot,
	Int_Rate_Type,
	Last_Rate_Chng_Dte,
	Last_Settle_Dte,
	Ln_Introducer_Code,
	Ln_Seq_Nbr,
	Ln_Type_Code,
	Ln_Use_Country,
	Maturity_Dte,
	Mortgage_Plan_Code,
	Repmt_Type_Code,
	Next_Pmt_Due_Dte,
	Od_Fixed_Int_Ind,
	Od_Grace_Period,
	Od_Int_Adj_Pct,
	Od_Int_Amt,
	Od_Int_Rate,
	Od_Prin_Amt,
	Od_Rate_Chng_Opt,
	Od_Rate_Type,
	Orig_Ln_Amt,
	OS_Od_Int_Amt,
	Os_Prin_Amt,
	Pmt_Due_Dte,
	Ppsl_Dte,
	Prod_Code,
	Project_Code,
	Promote_Code,
	Purpose_Of_Fin_HKMA,
	Rate_Chng_Eff_Dte,
	Rate_Chng_Opt,
	Repmt_Method_Code,
	Reprice_Option,
	Solicitor_Code,
	Tenor,
	Written_Off_Amt,
	Written_Off_Dte,
	{{  full_valid_flag(['__NoFutureDate_valid_Int_Start_Dte','__NoFutureDate_valid_Last_Rate_Chng_Dte','__NoFutureDate_valid_Last_Settle_Dte','__Future_Date_valid_Maturity_Dte','__Future_Date_valid_Pmt_Due_Dte','__Future_Date_valid_Ppsl_Dte','__NoFutureDate_valid_Rate_Chng_Eff_Dte'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
