WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-dev-00.bqd_015_raw.tag_br_fin_event_raw 
),   
 
CTE_2  AS  ( 
SELECT
	SAFE_CAST(Acct_Nbr  AS  INT64)  AS  Acct_Nbr,
	SAFE_CAST(Appl_Id  AS  STRING)  AS  Appl_Id,
	SAFE_CAST(Control_Fields  AS  STRING)  AS  Control_Fields,
	SAFE_CAST(Trx_Nbr  AS  STRING)  AS  Trx_Nbr,
	SAFE_CAST(Acct_Amt  AS  NUMERIC)  AS  Acct_Amt,
	SAFE_CAST(Acct_Ccy_Code  AS  STRING)  AS  Acct_Ccy_Code,
	SAFE_CAST(Acct_Handling_Br_Code  AS  STRING)  AS  Acct_Handling_Br_Code,
	SAFE_CAST(Begin_Bal_Amt  AS  NUMERIC)  AS  Begin_Bal_Amt,
	SAFE_CAST(Cash_Trx_Ind  AS  STRING)  AS  Cash_Trx_Ind,
	SAFE_CAST(Chq_Nbr  AS  NUMERIC)  AS  Chq_Nbr,
	SAFE_CAST(Chq_Type  AS  STRING)  AS  Chq_Type,
	SAFE_CAST(CNH_Rate_Ind  AS  STRING)  AS  CNH_Rate_Ind,
	SAFE_CAST(CNY_Trx_Amt_Override_Ind  AS  STRING)  AS  CNY_Trx_Amt_Override_Ind,
	SAFE_CAST(CNY_Trx_Cnt_Override_Ind  AS  STRING)  AS  CNY_Trx_Cnt_Override_Ind,
	SAFE_CAST(Correction_Ind  AS  STRING)  AS  Correction_Ind,
	SAFE_CAST(Counter_Ex_Rate  AS  NUMERIC)  AS  Counter_Ex_Rate,
	SAFE_CAST(Event_Actv_Type_Code  AS  STRING)  AS  Event_Actv_Type_Code,
	SAFE_CAST(Event_Amt  AS  NUMERIC)  AS  Event_Amt,
	SAFE_CAST(Event_Amt_Hke  AS  NUMERIC)  AS  Event_Amt_Hke,
	SAFE_CAST(Event_Ccy_Code  AS  STRING)  AS  Event_Ccy_Code,
	SAFE_CAST(Event_Centre  AS  STRING)  AS  Event_Centre,
	SAFE_CAST(Event_Chnl  AS  STRING)  AS  Event_Chnl,
	SAFE_CAST(Event_Dte  AS  DATE)  AS  Event_Dte,
	SAFE_CAST(Event_Ex_Rate  AS  NUMERIC)  AS  Event_Ex_Rate,
	SAFE_CAST(Event_Narrative  AS  STRING)  AS  Event_Narrative,
	SAFE_CAST(Event_Posted_Ind  AS  STRING)  AS  Event_Posted_Ind,
	SAFE_CAST(Event_Time  AS  INT64)  AS  Event_Time,
	SAFE_CAST(MSOF_Ref  AS  STRING)  AS  MSOF_Ref,
	SAFE_CAST(Passbook_Trx_Ref  AS  STRING)  AS  Passbook_Trx_Ref,
	SAFE_CAST(POF_Remarks  AS  STRING)  AS  POF_Remarks,
	SAFE_CAST(Purpose_Of_Fund  AS  STRING)  AS  Purpose_Of_Fund,
	SAFE_CAST(Rel_to_Acct_Hldr  AS  STRING)  AS  Rel_to_Acct_Hldr,
	SAFE_CAST(Source_Of_Fund  AS  STRING)  AS  Source_Of_Fund,
	SAFE_CAST(Stmt_Trx_Ref_1  AS  STRING)  AS  Stmt_Trx_Ref_1,
	SAFE_CAST(Stmt_Trx_Ref_2  AS  STRING)  AS  Stmt_Trx_Ref_2,
	SAFE_CAST(Stmt_Trx_Ref_3  AS  STRING)  AS  Stmt_Trx_Ref_3,
	SAFE_CAST(Third_Party_Trx_Ind  AS  STRING)  AS  Third_Party_Trx_Ind,
	SAFE_CAST(Trade_Certified_Code  AS  STRING)  AS  Trade_Certified_Code,
	SAFE_CAST(Trade_Ind  AS  STRING)  AS  Trade_Ind,
	SAFE_CAST(User_Id  AS  STRING)  AS  User_Id,
	SAFE_CAST(Val_Dte  AS  DATE)  AS  Val_Dte
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_01YN('Cash_Trx_Ind')}},
	{{validate_01YN('CNH_Rate_Ind')}},
	{{validate_01YN('CNY_Trx_Amt_Override_Ind')}},
	{{validate_01YN('CNY_Trx_Cnt_Override_Ind')}},
	{{validate_01YN('Correction_Ind')}},
	{{validate_01YN('Event_Posted_Ind')}},
	{{validate_01YN('Third_Party_Trx_Ind')}},
	{{validate_01YN('Trade_Ind')}},
	{{validate_Future_Date('Val_Dte')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
	Acct_Nbr,
	Appl_Id,
	Control_Fields,
	Trx_Nbr,
	Acct_Amt,
	Acct_Ccy_Code,
	Acct_Handling_Br_Code,
	Begin_Bal_Amt,
	Cash_Trx_Ind,
	Chq_Nbr,
	Chq_Type,
	CNH_Rate_Ind,
	CNY_Trx_Amt_Override_Ind,
	CNY_Trx_Cnt_Override_Ind,
	Correction_Ind,
	Counter_Ex_Rate,
	Event_Actv_Type_Code,
	Event_Amt,
	Event_Amt_Hke,
	Event_Ccy_Code,
	Event_Centre,
	Event_Chnl,
	Event_Dte,
	Event_Ex_Rate,
	Event_Narrative,
	Event_Posted_Ind,
	Event_Time,
	MSOF_Ref,
	Passbook_Trx_Ref,
	POF_Remarks,
	Purpose_Of_Fund,
	Rel_to_Acct_Hldr,
	Source_Of_Fund,
	Stmt_Trx_Ref_1,
	Stmt_Trx_Ref_2,
	Stmt_Trx_Ref_3,
	Third_Party_Trx_Ind,
	Trade_Certified_Code,
	Trade_Ind,
	User_Id,
	Val_Dte,
	{{  full_valid_flag(['__01YN_valid_Cash_Trx_Ind','__01YN_valid_CNH_Rate_Ind','__01YN_valid_CNY_Trx_Amt_Override_Ind','__01YN_valid_CNY_Trx_Cnt_Override_Ind','__01YN_valid_Correction_Ind','__01YN_valid_Event_Posted_Ind','__01YN_valid_Third_Party_Trx_Ind','__01YN_valid_Trade_Ind','__Future_Date_valid_Val_Dte'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
