WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-dev-00.bqd_015_raw.tag_mpf_nonfin_event_raw 
),   
 
CTE_2  AS  ( 
SELECT
	SAFE_CAST(Event_Id  AS  STRING)  AS  Event_Id,
	SAFE_CAST(Buy_Fund_Code  AS  STRING)  AS  Buy_Fund_Code,
	SAFE_CAST(Cheque_Message_Code  AS  STRING)  AS  Cheque_Message_Code,
	SAFE_CAST(Confirmed_Dte  AS  DATE)  AS  Confirmed_Dte,
	SAFE_CAST(Contrib_Batch_Nbr  AS  STRING)  AS  Contrib_Batch_Nbr,
	SAFE_CAST(Contrib_Bill_Type_Code  AS  STRING)  AS  Contrib_Bill_Type_Code,
	SAFE_CAST(Contrib_Upto_Dte  AS  DATE)  AS  Contrib_Upto_Dte,
	SAFE_CAST(Cover_Fr_Dte  AS  DATE)  AS  Cover_Fr_Dte,
	SAFE_CAST(Cover_To_Dte  AS  DATE)  AS  Cover_To_Dte,
	SAFE_CAST(Eff_Dte  AS  DATE)  AS  Eff_Dte,
	SAFE_CAST(Er_Acct_Nbr  AS  STRING)  AS  Er_Acct_Nbr,
	SAFE_CAST(Er_Appl_Id  AS  STRING)  AS  Er_Appl_Id,
	SAFE_CAST(Er_Ee_Ind  AS  STRING)  AS  Er_Ee_Ind,
	SAFE_CAST(Er_Control_Fields  AS  STRING)  AS  Er_Control_Fields,
	SAFE_CAST(Lsp_Amt  AS  NUMERIC)  AS  Lsp_Amt,
	SAFE_CAST(Lsp_Ind  AS  STRING)  AS  Lsp_Ind,
	SAFE_CAST(Lsp_To_Ind  AS  STRING)  AS  Lsp_To_Ind,
	SAFE_CAST(Mpf_Orso_Ind  AS  STRING)  AS  Mpf_Orso_Ind,
	SAFE_CAST(Mpf_Plan_Type_Code  AS  STRING)  AS  Mpf_Plan_Type_Code,
	SAFE_CAST(Own_Trustee_Ind  AS  STRING)  AS  Own_Trustee_Ind,
	SAFE_CAST(Overpmt_Payee_Ind  AS  STRING)  AS  Overpmt_Payee_Ind,
	SAFE_CAST(Overpmt_Er_Amt  AS  NUMERIC)  AS  Overpmt_Er_Amt,
	SAFE_CAST(Overpmt_Ee_Amt  AS  NUMERIC)  AS  Overpmt_Ee_Amt,
	SAFE_CAST(Payee_Type_Ind  AS  STRING)  AS  Payee_Type_Ind,
	SAFE_CAST(Partial_Full_Term_Ind  AS  STRING)  AS  Partial_Full_Term_Ind,
	SAFE_CAST(Plan_Nbr  AS  STRING)  AS  Plan_Nbr,
	SAFE_CAST(Pct  AS  NUMERIC)  AS  Pct,
	SAFE_CAST(Pmt_Method_Code  AS  STRING)  AS  Pmt_Method_Code,
	SAFE_CAST(Pmt_Nbr  AS  STRING)  AS  Pmt_Nbr,
	SAFE_CAST(Pmt_Ref  AS  STRING)  AS  Pmt_Ref,
	SAFE_CAST(Pmt_Type_Code  AS  STRING)  AS  Pmt_Type_Code,
	SAFE_CAST(Relevant_Income  AS  NUMERIC)  AS  Relevant_Income,
	SAFE_CAST(Scheme_Nbr  AS  STRING)  AS  Scheme_Nbr,
	SAFE_CAST(Sell_Fund_Code  AS  STRING)  AS  Sell_Fund_Code,
	SAFE_CAST(Susp_Type_Code  AS  STRING)  AS  Susp_Type_Code,
	SAFE_CAST(Term_Reason_Code  AS  STRING)  AS  Term_Reason_Code,
	SAFE_CAST(To_Other_Register_Scheme_ind  AS  STRING)  AS  To_Other_Register_Scheme_ind,
	SAFE_CAST(To_Plan_Nbr  AS  STRING)  AS  To_Plan_Nbr,
	SAFE_CAST(To_Scheme_Dte  AS  DATE)  AS  To_Scheme_Dte,
	SAFE_CAST(To_Scheme_Type  AS  STRING)  AS  To_Scheme_Type,
	SAFE_CAST(To_Trust_Code  AS  STRING)  AS  To_Trust_Code,
	SAFE_CAST(Tran_Amt  AS  NUMERIC)  AS  Tran_Amt,
	SAFE_CAST(Transfer_Mode  AS  STRING)  AS  Transfer_Mode,
	SAFE_CAST(Trust_Reg_Nbr  AS  STRING)  AS  Trust_Reg_Nbr,
	SAFE_CAST(Trustee_Code  AS  STRING)  AS  Trustee_Code,
	SAFE_CAST(Unit_Value  AS  NUMERIC)  AS  Unit_Value,
	SAFE_CAST(Vol_Cont_To_Trustee_Ind  AS  STRING)  AS  Vol_Cont_To_Trustee_Ind
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_NoFutureDate('Confirmed_Dte')}},
	{{validate_NoFutureDate('Contrib_Upto_Dte')}},
	{{validate_Future_Date('Cover_Fr_Dte')}},
	{{validate_Future_Date('Cover_To_Dte')}},
	{{validate_Future_Date('Eff_Dte')}},
	{{validate_Future_Date('To_Scheme_Dte')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
	Event_Id,
	Buy_Fund_Code,
	Cheque_Message_Code,
	Confirmed_Dte,
	Contrib_Batch_Nbr,
	Contrib_Bill_Type_Code,
	Contrib_Upto_Dte,
	Cover_Fr_Dte,
	Cover_To_Dte,
	Eff_Dte,
	Er_Acct_Nbr,
	Er_Appl_Id,
	Er_Ee_Ind,
	Er_Control_Fields,
	Lsp_Amt,
	Lsp_Ind,
	Lsp_To_Ind,
	Mpf_Orso_Ind,
	Mpf_Plan_Type_Code,
	Own_Trustee_Ind,
	Overpmt_Payee_Ind,
	Overpmt_Er_Amt,
	Overpmt_Ee_Amt,
	Payee_Type_Ind,
	Partial_Full_Term_Ind,
	Plan_Nbr,
	Pct,
	Pmt_Method_Code,
	Pmt_Nbr,
	Pmt_Ref,
	Pmt_Type_Code,
	Relevant_Income,
	Scheme_Nbr,
	Sell_Fund_Code,
	Susp_Type_Code,
	Term_Reason_Code,
	To_Other_Register_Scheme_ind,
	To_Plan_Nbr,
	To_Scheme_Dte,
	To_Scheme_Type,
	To_Trust_Code,
	Tran_Amt,
	Transfer_Mode,
	Trust_Reg_Nbr,
	Trustee_Code,
	Unit_Value,
	Vol_Cont_To_Trustee_Ind,
	{{  full_valid_flag(['__NoFutureDate_valid_Confirmed_Dte','__NoFutureDate_valid_Contrib_Upto_Dte','__Future_Date_valid_Cover_Fr_Dte','__Future_Date_valid_Cover_To_Dte','__Future_Date_valid_Eff_Dte','__Future_Date_valid_To_Scheme_Dte'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
