WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-dev-00.bqd_015_raw.tag_rci_invest_event_raw 
),   
 
CTE_2  AS  ( 
SELECT
	SAFE_CAST(Trx_Linked_Ref  AS  STRING)  AS  Trx_Linked_Ref,
	SAFE_CAST(Prod_Code  AS  STRING)  AS  Prod_Code,
	SAFE_CAST(Source_Id  AS  STRING)  AS  Source_Id,
	SAFE_CAST(Acct_Nbr  AS  INT64)  AS  Acct_Nbr,
	SAFE_CAST(AP_Ind  AS  STRING)  AS  AP_Ind,
	SAFE_CAST(Appl_Id  AS  STRING)  AS  Appl_Id,
	SAFE_CAST(Asset_Concentration_Ind  AS  STRING)  AS  Asset_Concentration_Ind,
	SAFE_CAST(Asset_Concentration_Reason  AS  STRING)  AS  Asset_Concentration_Reason,
	SAFE_CAST(Asset_Concentration_Reason_Remark  AS  STRING)  AS  Asset_Concentration_Reason_Remark,
	SAFE_CAST(Audio_Record_Ind  AS  STRING)  AS  Audio_Record_Ind,
	SAFE_CAST(Chnl_Id  AS  STRING)  AS  Chnl_Id,
	SAFE_CAST(Chnl_Type_Code  AS  STRING)  AS  Chnl_Type_Code,
	SAFE_CAST(Control_Fields  AS  STRING)  AS  Control_Fields,
	SAFE_CAST(Cust_Objective_Ind  AS  STRING)  AS  Cust_Objective_Ind,
	SAFE_CAST(Doc_Nbr  AS  INT64)  AS  Doc_Nbr,
	SAFE_CAST(Doc_Type_Code  AS  STRING)  AS  Doc_Type_Code,
	SAFE_CAST(Event_Br_Code  AS  STRING)  AS  Event_Br_Code,
	SAFE_CAST(Event_Seller_Id  AS  STRING)  AS  Event_Seller_Id,
	SAFE_CAST(Frequent_Trader_Ind  AS  STRING)  AS  Frequent_Trader_Ind,
	SAFE_CAST(Frequent_Trader_Reason  AS  STRING)  AS  Frequent_Trader_Reason,
	SAFE_CAST(Frequent_Trader_Reason_Remark  AS  STRING)  AS  Frequent_Trader_Reason_Remark,
	SAFE_CAST(Fund_Type_Code  AS  STRING)  AS  Fund_Type_Code,
	SAFE_CAST(Fund_Type_Desc  AS  STRING)  AS  Fund_Type_Desc,
	SAFE_CAST(Issue_Country_Code  AS  STRING)  AS  Issue_Country_Code,
	SAFE_CAST(Objective_Mismatch_Ind  AS  STRING)  AS  Objective_Mismatch_Ind,
	SAFE_CAST(Objective_Mismatch_Reason  AS  STRING)  AS  Objective_Mismatch_Reason,
	SAFE_CAST(Objective_Mismatch_Reason_Remark  AS  STRING)  AS  Objective_Mismatch_Reason_Remark,
	SAFE_CAST(Order_Type_Ind  AS  STRING)  AS  Order_Type_Ind,
	SAFE_CAST(Prod_Name  AS  STRING)  AS  Prod_Name,
	SAFE_CAST(Prod_Objective_Ind  AS  STRING)  AS  Prod_Objective_Ind,
	SAFE_CAST(Prod_Risk_Rating  AS  STRING)  AS  Prod_Risk_Rating,
	SAFE_CAST(Prod_Tenor  AS  STRING)  AS  Prod_Tenor,
	SAFE_CAST(Quest_ID  AS  STRING)  AS  Quest_ID,
	SAFE_CAST(Risk_Disclosure_Ind  AS  STRING)  AS  Risk_Disclosure_Ind,
	SAFE_CAST(Risk_Mismatch_Ind  AS  STRING)  AS  Risk_Mismatch_Ind,
	SAFE_CAST(Risk_Mismatch_Reason  AS  STRING)  AS  Risk_Mismatch_Reason,
	SAFE_CAST(Risk_Mismatch_Reason_Remark  AS  STRING)  AS  Risk_Mismatch_Reason_Remark,
	SAFE_CAST(Same_Fund_Switch_Ind  AS  STRING)  AS  Same_Fund_Switch_Ind,
	SAFE_CAST(Same_Fund_Switch_Reason  AS  STRING)  AS  Same_Fund_Switch_Reason,
	SAFE_CAST(Same_Fund_Switch_Reason_Remark  AS  STRING)  AS  Same_Fund_Switch_Reason_Remark,
	SAFE_CAST(Short_Hold_Ind  AS  STRING)  AS  Short_Hold_Ind,
	SAFE_CAST(Short_Hold_Period  AS  STRING)  AS  Short_Hold_Period,
	SAFE_CAST(Short_Hold_Reason  AS  STRING)  AS  Short_Hold_Reason,
	SAFE_CAST(Short_Hold_Reason_Remark  AS  STRING)  AS  Short_Hold_Reason_Remark,
	SAFE_CAST(Tenor_Mismatch_Ind  AS  STRING)  AS  Tenor_Mismatch_Ind,
	SAFE_CAST(Tenor_Mismatch_Reason  AS  STRING)  AS  Tenor_Mismatch_Reason,
	SAFE_CAST(Tenor_Mismatch_Reason_Remark  AS  STRING)  AS  Tenor_Mismatch_Reason_Remark,
	SAFE_CAST(VC_AS  AS  STRING)  AS  VC_AS,
	SAFE_CAST(Vul_Cust  AS  STRING)  AS  Vul_Cust,
	SAFE_CAST(Vul_Cust_Optout_Witness_Ind  AS  STRING)  AS  Vul_Cust_Optout_Witness_Ind,
	SAFE_CAST(Witness_Arrange  AS  STRING)  AS  Witness_Arrange
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_HKID('Doc_Type_Code','Doc_Nbr')}},
	{{validate_DocTypeCode('Doc_Type_Code')}},
	{{validate_CountryCode('Issue_Country_Code')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
	Trx_Linked_Ref,
	Prod_Code,
	Source_Id,
	Acct_Nbr,
	AP_Ind,
	Appl_Id,
	Asset_Concentration_Ind,
	Asset_Concentration_Reason,
	Asset_Concentration_Reason_Remark,
	Audio_Record_Ind,
	Chnl_Id,
	Chnl_Type_Code,
	Control_Fields,
	Cust_Objective_Ind,
	Doc_Nbr,
	Doc_Type_Code,
	Event_Br_Code,
	Event_Seller_Id,
	Frequent_Trader_Ind,
	Frequent_Trader_Reason,
	Frequent_Trader_Reason_Remark,
	Fund_Type_Code,
	Fund_Type_Desc,
	Issue_Country_Code,
	Objective_Mismatch_Ind,
	Objective_Mismatch_Reason,
	Objective_Mismatch_Reason_Remark,
	Order_Type_Ind,
	Prod_Name,
	Prod_Objective_Ind,
	Prod_Risk_Rating,
	Prod_Tenor,
	Quest_ID,
	Risk_Disclosure_Ind,
	Risk_Mismatch_Ind,
	Risk_Mismatch_Reason,
	Risk_Mismatch_Reason_Remark,
	Same_Fund_Switch_Ind,
	Same_Fund_Switch_Reason,
	Same_Fund_Switch_Reason_Remark,
	Short_Hold_Ind,
	Short_Hold_Period,
	Short_Hold_Reason,
	Short_Hold_Reason_Remark,
	Tenor_Mismatch_Ind,
	Tenor_Mismatch_Reason,
	Tenor_Mismatch_Reason_Remark,
	VC_AS,
	Vul_Cust,
	Vul_Cust_Optout_Witness_Ind,
	Witness_Arrange,
	{{  full_valid_flag(['__HKID_valid_Doc_Nbr','__DocTypeCode_valid_Doc_Type_Code','__CountryCode_valid_Issue_Country_Code'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
