WITH  CTE_1  AS(   
SELECT 
	* 
FROM  gcp-prj-dat-bigquery-dev-00.bqd_015_raw.tag_other_bank_trf_event_raw 
),   
 
CTE_2  AS  ( 
SELECT
	SAFE_CAST(Event_Id  AS  STRING)  AS  Event_Id,
	SAFE_CAST(Applicant_Name  AS  STRING)  AS  Applicant_Name,
	SAFE_CAST(Applicant_Place_of_Operation  AS  STRING)  AS  Applicant_Place_of_Operation,
	SAFE_CAST(Applicant_Place_Of_Origin  AS  STRING)  AS  Applicant_Place_Of_Origin,
	SAFE_CAST(Backdate_Ind  AS  STRING)  AS  Backdate_Ind,
	SAFE_CAST(Bank_To_Bank_Info  AS  STRING)  AS  Bank_To_Bank_Info,
	SAFE_CAST(BEA_China_Br_Code  AS  STRING)  AS  BEA_China_Br_Code,
	SAFE_CAST(Ben_Acct_Nbr  AS  STRING)  AS  Ben_Acct_Nbr,
	SAFE_CAST(Ben_Country_Code  AS  STRING)  AS  Ben_Country_Code,
	SAFE_CAST(Ben_Instit_Country_Code  AS  STRING)  AS  Ben_Instit_Country_Code,
	SAFE_CAST(Ben_Instit_Info  AS  STRING)  AS  Ben_Instit_Info,
	SAFE_CAST(Ben_Instit_Name  AS  STRING)  AS  Ben_Instit_Name,
	SAFE_CAST(Ben_Name  AS  STRING)  AS  Ben_Name,
	SAFE_CAST(Ccy_Code  AS  STRING)  AS  Ccy_Code,
	SAFE_CAST(Clearing_Bank_Code  AS  STRING)  AS  Clearing_Bank_Code,
	SAFE_CAST(CNAPS_Ind  AS  STRING)  AS  CNAPS_Ind,
	SAFE_CAST(CNH_Rate_Ind  AS  STRING)  AS  CNH_Rate_Ind,
	SAFE_CAST(CNY_TT_Categ_Code  AS  STRING)  AS  CNY_TT_Categ_Code,
	SAFE_CAST(CNY_TT_Trade_Ind  AS  STRING)  AS  CNY_TT_Trade_Ind,
	SAFE_CAST(Covering_Bank_Code  AS  STRING)  AS  Covering_Bank_Code,
	SAFE_CAST(Credit_Dte  AS  DATE)  AS  Credit_Dte,
	SAFE_CAST(Eff_Dte  AS  DATE)  AS  Eff_Dte,
	SAFE_CAST(Event_Amt  AS  NUMERIC)  AS  Event_Amt,
	SAFE_CAST(Event_Amt_Hke  AS  NUMERIC)  AS  Event_Amt_Hke,
	SAFE_CAST(Event_Rem  AS  STRING)  AS  Event_Rem,
	SAFE_CAST(Event_Rem2  AS  STRING)  AS  Event_Rem2,
	SAFE_CAST(Ext_Cust_Country_Code  AS  STRING)  AS  Ext_Cust_Country_Code,
	SAFE_CAST(Ext_Cust_Info  AS  STRING)  AS  Ext_Cust_Info,
	SAFE_CAST(FFM_Ovr_Id  AS  STRING)  AS  FFM_Ovr_Id,
	SAFE_CAST(GCO_Waived_Ind  AS  STRING)  AS  GCO_Waived_Ind,
	SAFE_CAST(HIT_Ind  AS  STRING)  AS  HIT_Ind,
	SAFE_CAST(HKID_Resident_Ind  AS  STRING)  AS  HKID_Resident_Ind,
	SAFE_CAST(HKL_Message_Ind  AS  STRING)  AS  HKL_Message_Ind,
	SAFE_CAST(Instit_Country_Code  AS  STRING)  AS  Instit_Country_Code,
	SAFE_CAST(Instit_Info  AS  STRING)  AS  Instit_Info,
	SAFE_CAST(Instit_Info_Id  AS  STRING)  AS  Instit_Info_Id,
	SAFE_CAST(Instit_Info_Rem  AS  STRING)  AS  Instit_Info_Rem,
	SAFE_CAST(Inter_Bank_Country_Code  AS  STRING)  AS  Inter_Bank_Country_Code,
	SAFE_CAST(Inter_Bank_Info  AS  STRING)  AS  Inter_Bank_Info,
	SAFE_CAST(Msg_Type  AS  STRING)  AS  Msg_Type,
	SAFE_CAST(MT191_Ind  AS  STRING)  AS  MT191_Ind,
	SAFE_CAST(MT910_Ind  AS  STRING)  AS  MT910_Ind,
	SAFE_CAST(Net_Pay_Amt  AS  NUMERIC)  AS  Net_Pay_Amt,
	SAFE_CAST(Net_Pay_Ccy_Code  AS  STRING)  AS  Net_Pay_Ccy_Code,
	SAFE_CAST(Net_Proceeds  AS  NUMERIC)  AS  Net_Proceeds,
	SAFE_CAST(Net_Proceeds_Hke  AS  NUMERIC)  AS  Net_Proceeds_Hke,
	SAFE_CAST(New_Fund_Ind  AS  STRING)  AS  New_Fund_Ind,
	SAFE_CAST(Other_Bank_Acct_Nbr  AS  STRING)  AS  Other_Bank_Acct_Nbr,
	SAFE_CAST(Paying_Bank_Code  AS  STRING)  AS  Paying_Bank_Code,
	SAFE_CAST(Pmt_Code  AS  STRING)  AS  Pmt_Code,
	SAFE_CAST(Pmt_Method_Code  AS  STRING)  AS  Pmt_Method_Code,
	SAFE_CAST(POF_Remarks  AS  STRING)  AS  POF_Remarks,
	SAFE_CAST(Purpose_Of_Fund  AS  STRING)  AS  Purpose_Of_Fund,
	SAFE_CAST(Purpose_Of_Fund_Remarks  AS  STRING)  AS  Purpose_Of_Fund_Remarks,
	SAFE_CAST(Purpose_Of_Pmt_BH  AS  STRING)  AS  Purpose_Of_Pmt_BH,
	SAFE_CAST(Purpose_Of_Pmt_UAE  AS  STRING)  AS  Purpose_Of_Pmt_UAE,
	SAFE_CAST(Receiver_Corr  AS  STRING)  AS  Receiver_Corr,
	SAFE_CAST(Receiver_Corr_Bank_Id  AS  STRING)  AS  Receiver_Corr_Bank_Id,
	SAFE_CAST(Reject_Reason_Code  AS  STRING)  AS  Reject_Reason_Code,
	SAFE_CAST(Rel_to_Acct_Hldr  AS  STRING)  AS  Rel_to_Acct_Hldr,
	SAFE_CAST(Rel_to_Acct_Hldr_Remarks  AS  STRING)  AS  Rel_to_Acct_Hldr_Remarks,
	SAFE_CAST(Related_Acct_Nbr  AS  INT64)  AS  Related_Acct_Nbr,
	SAFE_CAST(Related_Appl_Id  AS  STRING)  AS  Related_Appl_Id,
	SAFE_CAST(Related_Control_Fields  AS  STRING)  AS  Related_Control_Fields,
	SAFE_CAST(Return_Reason  AS  STRING)  AS  Return_Reason,
	SAFE_CAST(Settle_Method  AS  STRING)  AS  Settle_Method,
	SAFE_CAST(Sgold_Ind  AS  STRING)  AS  Sgold_Ind,
	SAFE_CAST(SLA_Id  AS  STRING)  AS  SLA_Id,
	SAFE_CAST(Source_Of_Fund  AS  STRING)  AS  Source_Of_Fund,
	SAFE_CAST(Source_Of_Fund_Remarks  AS  STRING)  AS  Source_Of_Fund_Remarks,
	SAFE_CAST(Stf_Nbr  AS  STRING)  AS  Stf_Nbr,
	SAFE_CAST(Trade_Certified_Code  AS  STRING)  AS  Trade_Certified_Code,
	SAFE_CAST(Trade_Ind  AS  STRING)  AS  Trade_Ind,
	SAFE_CAST(Treasury_Ref  AS  STRING)  AS  Treasury_Ref,
	SAFE_CAST(UETR  AS  STRING)  AS  UETR,
	SAFE_CAST(Ultimate_Instit_Country_Code  AS  STRING)  AS  Ultimate_Instit_Country_Code,
	SAFE_CAST(Ultimate_Instit_Info  AS  STRING)  AS  Ultimate_Instit_Info,
	SAFE_CAST(Ultimate_Instit_Info_Id  AS  STRING)  AS  Ultimate_Instit_Info_Id,
	SAFE_CAST(Ultimate_Instit_Info_Rem  AS  STRING)  AS  Ultimate_Instit_Info_Rem
FROM  CTE_1 
),   
 
CTE_3  AS  ( 
	SELECT   
	*,
	{{validate_Backdate_Ind('Backdate_Ind')}},
	{{validate_Max_len_10('Ben_Acct_Nbr')}},
	{{validate_CountryCode('Ben_Country_Code')}},
	{{validate_CountryCode('Ben_Instit_Country_Code')}},
	{{validate_NoFutureDate('Credit_Dte')}},
	{{validate_Future_Date('Eff_Dte')}},
	{{validate_CountryCode('Ext_Cust_Country_Code')}},
	{{validate_CountryCode('Instit_Country_Code')}},
	{{validate_CountryCode('Inter_Bank_Country_Code')}},
	{{validate_Max_len_10('Other_Bank_Acct_Nbr')}},
	{{validate_Max_len_15('Related_Acct_Nbr')}},
	{{validate_Max_len_8('Stf_Nbr')}},
	{{validate_CountryCode('Ultimate_Instit_Country_Code')}}
FROM  CTE_2 
),   
 
CTE_4  AS  ( 
SELECT
	Event_Id,
	Applicant_Name,
	Applicant_Place_of_Operation,
	Applicant_Place_Of_Origin,
	Backdate_Ind,
	Bank_To_Bank_Info,
	BEA_China_Br_Code,
	Ben_Acct_Nbr,
	Ben_Country_Code,
	Ben_Instit_Country_Code,
	Ben_Instit_Info,
	Ben_Instit_Name,
	Ben_Name,
	Ccy_Code,
	Clearing_Bank_Code,
	CNAPS_Ind,
	CNH_Rate_Ind,
	CNY_TT_Categ_Code,
	CNY_TT_Trade_Ind,
	Covering_Bank_Code,
	Credit_Dte,
	Eff_Dte,
	Event_Amt,
	Event_Amt_Hke,
	Event_Rem,
	Event_Rem2,
	Ext_Cust_Country_Code,
	Ext_Cust_Info,
	FFM_Ovr_Id,
	GCO_Waived_Ind,
	HIT_Ind,
	HKID_Resident_Ind,
	HKL_Message_Ind,
	Instit_Country_Code,
	Instit_Info,
	Instit_Info_Id,
	Instit_Info_Rem,
	Inter_Bank_Country_Code,
	Inter_Bank_Info,
	Msg_Type,
	MT191_Ind,
	MT910_Ind,
	Net_Pay_Amt,
	Net_Pay_Ccy_Code,
	Net_Proceeds,
	Net_Proceeds_Hke,
	New_Fund_Ind,
	Other_Bank_Acct_Nbr,
	Paying_Bank_Code,
	Pmt_Code,
	Pmt_Method_Code,
	POF_Remarks,
	Purpose_Of_Fund,
	Purpose_Of_Fund_Remarks,
	Purpose_Of_Pmt_BH,
	Purpose_Of_Pmt_UAE,
	Receiver_Corr,
	Receiver_Corr_Bank_Id,
	Reject_Reason_Code,
	Rel_to_Acct_Hldr,
	Rel_to_Acct_Hldr_Remarks,
	Related_Acct_Nbr,
	Related_Appl_Id,
	Related_Control_Fields,
	Return_Reason,
	Settle_Method,
	Sgold_Ind,
	SLA_Id,
	Source_Of_Fund,
	Source_Of_Fund_Remarks,
	Stf_Nbr,
	Trade_Certified_Code,
	Trade_Ind,
	Treasury_Ref,
	UETR,
	Ultimate_Instit_Country_Code,
	Ultimate_Instit_Info,
	Ultimate_Instit_Info_Id,
	Ultimate_Instit_Info_Rem,
	{{  full_valid_flag(['__Backdate_Ind_valid_Backdate_Ind','__Max_len_10_valid_Ben_Acct_Nbr','__CountryCode_valid_Ben_Country_Code','__CountryCode_valid_Ben_Instit_Country_Code','__NoFutureDate_valid_Credit_Dte','__Future_Date_valid_Eff_Dte','__CountryCode_valid_Ext_Cust_Country_Code','__CountryCode_valid_Instit_Country_Code','__CountryCode_valid_Inter_Bank_Country_Code','__Max_len_10_valid_Other_Bank_Acct_Nbr','__Max_len_15_valid_Related_Acct_Nbr','__Max_len_8_valid_Stf_Nbr','__CountryCode_valid_Ultimate_Instit_Country_Code'])  }}
FROM  CTE_3)
 
SELECT  *  FROM  CTE_4
