CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_other_chq_event_raw`  (
Acct_Nbr  STRING(18),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Chq_Nbr  STRING(14),
Chq_Prefix_Nbr  STRING(1),
Chq_Seq_Nbr  STRING(5),
Chq_Ccy_Code  STRING(3),
Event_Dte  STRING(8),
Trx_Nbr  STRING(9),
Acct_Ccy_Code  STRING(3),
Appl_Doc_Nbr  STRING(25),
Appl_Doc_Type_Code  STRING(1),
Appl_Issue_Country_Code  STRING(3),
Chq_Amt  STRING(15),
Chq_Status_Code  STRING(1),
Chq_Type  STRING(15),
Chq_Type_Code  STRING(2),
Last_Mod_Centre_Id  STRING(4),
Last_Mod_Offr_Id  STRING(8),
Last_Mod_Dte  STRING(8),
Last_Mod_Time  STRING(12),
MSOF_Ref  STRING(8),
POF_Remarks  STRING(25),
Purpose_Of_Fund  STRING(1),
Rel_to_Acct_Hldr  STRING(1),
Source_Of_Fund  STRING(1),
Trx_Dte  STRING(8),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
