CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_dr_card_raw`  (
Card_Issue_Dte  STRING(8),
Card_Nbr  STRING(19),
Card_Seq_Nbr  STRING(2),
Expiry_Dte  STRING(8),
Actvn_Dte  STRING(8),
Anl_Fee_Expiry_Dte  STRING(8),
Card_Delivery_Code  STRING(3),
Card_Hld_Type_Code  STRING(1),
Card_Retain_Atm_Nbr  STRING(4),
Card_Retain_Bank_Code  STRING(4),
Card_Retain_Dte  STRING(8),
Cash_Voucher_Last_Update_Dte  STRING(8),
Company_Type  STRING(2),
JC_Cash_Voucher_Ind  STRING(1),
Old_AIO_Prod_Code  STRING(4),
Old_Card_Seq_Nbr  STRING(2),
Pin_Issue_Dte  STRING(8),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
