CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_indv_raw`  (
Doc_Nbr  STRING(25),
Doc_Type_Code  STRING(2),
Issue_Country_Code  STRING(2),
Anl_Household_Income_Hke  STRING(15),
Car_Ind  STRING(1),
Check_Digit  STRING(1),
Citizenship  STRING(3),
Customer_Type_Code  STRING(10),
Dte_Of_Birth  STRING(8),
education_Code  STRING(3),
Flat_Owner_Ind  STRING(1),
Gender_Code  STRING(1),
Given_Name  STRING(40),
Given_Name_Full  STRING(200),
Has_Domestic_Helper_Ind  STRING(1),
Home_Country_Code  STRING(3),
Investment_Amt_Per_Mth_Hke  STRING(15),
Marital_Status  STRING(1),
Nationality  STRING(3),
Nbr_Of_Children  STRING(2),
Other_Name  STRING(30),
Place_Of_Birth  STRING(3),
Residential_Expns_Per_Mth_Hke  STRING(15),
Residential_Type_Code  STRING(3),
Saving_Amt_Per_Mth_Hke  STRING(15),
Smoker_Ind  STRING(1),
Surname  STRING(50),
Surname_Full  STRING(80),
Title_Code  STRING(2),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
