CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_mpf_employee_acct_raw`  (
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Control_Fields  STRING(16),
Broker_Code  STRING(20),
Classification_Code  STRING(4),
Employment_Dte  STRING(8),
First_Aprov_Dte  STRING(8),
Industry_Code  STRING(8),
Mand_Plan_Commission_Code  STRING(4),
Mand_Trf_Plan_Commission_Code  STRING(4),
Member_Nature_Code  STRING(1),
Nbr_Of_Fund_Choice_Chng  STRING(4),
Reg_Or_Casual_Employee_Ind  STRING(1),
Relevant_Income  STRING(15),
Skill_Type_Code  STRING(4),
Trust_Type_Code  STRING(4),
Volu_Plan_Commission_Code  STRING(4),
Volu_Trf_Plan_Commission_Code  STRING(4),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
