CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_insl_pmt_event_raw`  (
Event_Id  STRING(23),
Adj_Int_Amt  STRING(16),
Adj_Od_Int_Amt  STRING(16),
Due_Dte  STRING(8),
Gen_From  STRING(2),
Gov_Claim_Ind  STRING(1),
Gov_Reimburs_Amt  STRING(15),
Impair_Ind  STRING(1),
Insl_Nbr  STRING(3),
Int_Amt  STRING(15),
Nbr_Of_Insl_In_Arrear  STRING(3),
Pmt_Mode_Code  STRING(2),
Pmt_Nbr  STRING(4),
Pmt_Type_Code  STRING(2),
Prin_Amt  STRING(15),
Prin_Bal  STRING(15),
Rev_Dte  STRING(8),
Settle_Mode  STRING(2),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
