CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_ln_appl_raw`  (
Appl_Id  STRING(3),
Appl_Nbr  STRING(12),
Appl_Control_Fields  STRING(8),
Allow_Deviation_ATD_Ind  STRING(1),
Aprov_Lending_Centre_Id  STRING(10),
ATD  STRING(8),
Cancel_Dte  STRING(8),
Clean_Exposure_Income_Ratio  STRING(7),
Confirm_Dte  STRING(8),
Create_Dte  STRING(8),
Cust_CAP  STRING(7),
Cust_DSR  STRING(7),
Further_Review_Ind  STRING(1),
Ln_Collat_Ratio  STRING(7),
Ln_Income_Ratio  STRING(7),
Ln_Net_Purchase_Ratio  STRING(7),
Ln_Purchase_Ratio  STRING(7),
Net_Worth_Consider_Ind  STRING(1),
Prod_CAP  STRING(7),
Prod_DSR  STRING(7),
Refinc_FC_Ind  STRING(1),
Refinc_FC_Acct_Nbr  STRING(20),
Refinc_FC_Ln_Type  STRING(5),
Rej_Dte  STRING(8),
Review_Dte  STRING(8),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
