CREATE  OR  REPLACE  TABLE  `bqd_015_raw.tag_lds_acct_raw`  (
Acct_Nbr  STRING(20),
Appl_Id  STRING(3),
Control_Fields  STRING(8),
Accrued_Int_Amt  STRING(15),
Accrued_Int_Amt_Hke  STRING(15),
Alternate_Ccy_Code  STRING(3),
Collateral_Ind  STRING(3),
Coupon_Rate  STRING(12),
Determine_Dte  STRING(8),
Intl_dep_nbr  STRING(8),
Intl_Int_Rate  STRING(12),
Linked_Type_Code  STRING(8),
Mstr_Agreement_Dte  STRING(8),
Maturity_Amt  STRING(15),
Maturity_Dte  STRING(8),
Nbr_Of_Days  STRING(4),
Nbr_Of_Share  STRING(9),
Next_Coupon_Dte  STRING(8),
Periodic_Ind  STRING(1),
Profit_Amt  STRING(15),
Result_Code  STRING(3),
Settle_Dte  STRING(8),
Stock_Code  STRING(5),
Trade_Dte  STRING(8),
Type_Ref_Nbr  STRING(11),
__row_number  STRING,   
__sys_code  STRING,   
__file_name  STRING,   
__batch_date  TIMESTAMP,   
__load_date  TIMESTAMP,   
__load_type  STRING 
);
